### ISSUE TITLE
Odd one - Shows added, then removed?

### ISSUE THREAD

**Issue by bigdork** [mza921/Plex-Auto-Collections#124]
```
  CBS:
    sync_mode: sync
    studio: [CBS, CBS All Access, CBS Television Studios]
```
Behaves this way:
```
| Updating collection: CBS...
| Sync Mode: sync
| Processing Plex Search: studio(CBS OR CBS All Access OR CBS Television Studios)
| CBS Collection | + | The 100
| CBS Collection | + | 2 Broke Girls
| CBS Collection | + | 48 Hours
| CBS Collection | + | 48 Hours: NCIS
| CBS Collection | + | 60 Minutes
...
| Processed 307 Shows
| CBS Collection | - | 2 Broke Girls
| CBS Collection | - | 9JKL
| CBS Collection | - | 48 Hours
| CBS Collection | - | 48 Hours: NCIS
| CBS Collection | - | 60 Minutes
| CBS Collection | - | The 100
```
Am I missing something? Of note, the shows that got removed (before I broke the run) all had studio "CBS" -- too short to match? I've not gotten to other 3-or-less-letter networks yet...

**Comment by meisnate12** [comment]
ill look into this today

**Comment by meisnate12** [comment]
can you see if it does this on my PerformanceUpdate Branch of my cloned repo? Clone the repo [here](https://github.com/meisnate12/Plex-Auto-Collections) and then do a `git checkout PerformanceUpdate`

**Comment by bigdork** [comment]
Same
```
|===================================================================================================|
|     ___  _               _         _           ___       _  _           _    _                    |
|    | _ \| | ___ __ __   /_\  _  _ | |_  ___   / __| ___ | || | ___  __ | |_ (_) ___  _ _   ___    |
|    |  _/| |/ -_)\ \ /  / _ \| || ||  _|/ _ \ | (__ / _ \| || |/ -_)/ _||  _|| |/ _ \| ' \ (_-<    |
|    |_|  |_|\___|/_\_\ /_/ \_\\_,_| \__|\___/  \___|\___/|_||_|\___|\__| \__||_|\___/|_||_|/__/    |
|                                                                                                   |
|===================================================================================================|
| Version 2.6.1
...
| Sync Mode: sync
| Processing Plex Search: studio(CBS OR CBS All Access OR CBS Television Studios)
| CBS Collection | + | The 100
| CBS Collection | + | 2 Broke Girls
| CBS Collection | + | 48 Hours
| CBS Collection | + | 60 Minutes
| CBS Collection | + | 9JKL
...
| CBS Collection | + | Young Sheldon
| CBS Collection | + | Zoo
| Processed 308 Shows
| CBS Collection | - | 2 Broke Girls
| CBS Collection | - | 9JKL
| CBS Collection | - | 48 Hours
| CBS Collection | - | 60 Minutes
| CBS Collection | - | The 100

```
So far, all of these Add & Remove shows have had "CBS" as the studio, they report as being added even if they are already in the collection, then removed due to `sync_mode: sync`. I'm going to change to `sync_mode: append` for now, since the shows are added, but something is up.

**Comment by meisnate12** [comment]
your not quite pulling the right code if you do the version would say 2.7.0 did you check out the PerformanceUpdate branch after cloning

**Comment by meisnate12** [comment]
ok it actually looks like youre on the right branch you just need to do a git pull on that branch to update it to 2.7.0

**Comment by bigdork** [comment]
Deleted and started from scratch, won't run.
I am just no good with git...
```
$ git clone https://github.com/meisnate12/Plex-Auto-Collections.git
$ cd Plex-Auto-Collections/
~/Plex-Auto-Collections$ pip3 install -r requirements.txt
pg@mothership:~/Plex-Auto-Collections$ git checkout PerformanceUpdate
Branch 'PerformanceUpdate' set up to track remote branch 'PerformanceUpdate' from 'origin'.
Switched to a new branch 'PerformanceUpdate'
~/Plex-Auto-Collections$ python3 app/plex_auto_collections.py -c /opt/scripts/Plex-Auto-Collections/config/config.tv.networks.yml -u
Traceback (most recent call last):
  File "app/plex_auto_collections.py", line 15, in <module>
    from plex_tools import get_map
  File "/home/pg/Plex-Auto-Collections/app/plex_tools.py", line 7, in <module>
    import imdb_tools
  File "/home/pg/Plex-Auto-Collections/app/imdb_tools.py", line 17, in <module>
    from tmdbv3api import Trending
ImportError: cannot import name 'Trending'
```

**Comment by meisnate12** [comment]
do the update requirements on that branch and it should work

**Comment by bigdork** [comment]
*sigh* I'm such a newb.
Running now, I'll report back.

**Comment by meisnate12** [comment]
ok let me know how it goes

**Comment by bigdork** [comment]
Still reports adding shows (whether they were already a part of the collection or not) but only those that have studio simply "CBS"
Below is an example of Star Trek Shows. You can see the "CBS All Access" ones are recognized as already being a part of the collection `[=]` while the "CBS" ones are being added `[+]`. Later on, the "CBS" studio Star Trek shows are removed `[-]` (along with a couple hundred other shows)

```
| Version 2.7.0
...
| CBS Collection | + | Star Trek: Deep Space Nine
| CBS Collection | = | Star Trek: Discovery
| CBS Collection | = | Star Trek: Lower Decks
| CBS Collection | = | Star Trek: Picard
| CBS Collection | = | Star Trek: Short Treks
| CBS Collection | + | Star Trek: The Next Generation
...
| Processed 308 Shows
...
| CBS Collection | - | Star Trek: The Next Generation
| CBS Collection | - | Star Trek: Deep Space Nine
'''

**Comment by meisnate12** [comment]
I can't seem to replicate your error mine works just fine 
I set Animaniacs to CBS All Access and Archer to CBS Television Studios for this test 

I did a small change, I don't expect it to fix your problem but you never know so do a git pull on the branch and try again. did you try running just this collection by itself without any others in the config?

config.yml
```yml
collections:
  CBS:
    sync_mode: sync
    studio: [CBS, CBS All Access, CBS Television Studios]
```

output:
```
PS S:\Plex Auto Collections\app> python .\plex_auto_collections.py -u

|===================================================================================================|
|     ___  _               _         _           ___       _  _           _    _                    |
|    | _ \| | ___ __ __   /_\  _  _ | |_  ___   / __| ___ | || | ___  __ | |_ (_) ___  _ _   ___    |
|    |  _/| |/ -_)\ \ /  / _ \| || ||  _|/ _ \ | (__ / _ \| || |/ -_)/ _||  _|| |/ _ \| ' \ (_-<    |
|    |_|  |_|\___|/_\_\ /_/ \_\\_,_| \__|\___/  \___|\___/|_||_|\___|\__| \__||_|\___/|_||_|/__/    |
|                                                                                                   |
|===================================================================================================|
| Version 2.7.0
| Locating config...
| Using S:\Plex Auto Collections\app\config.yml as config
|===================================================================================================|
| Connecting to Plex...
| Config Error: plex sub-attribute sync_mode: add_only is an invalid input using append as default
|       append (Only Add Items to the Collection)
|       sync (Add & Remove Items from the Collection)
| Plex Connection Successful
|===================================================================================================|
| Connecting to TMDb...
| TMDb Connection Successful
|===================================================================================================|
| Connecting to tautulli...
| tautulli Connection Successful
|===================================================================================================|
| Connecting to Trakt...
| Trakt Connection Successful
|===================================================================================================|
| Connecting to Radarr...
| Config Error: radarr sub-attribute quality_profile_id is blank
| Config Error: radarr sub-attribute root_folder_path is blank
| Config Error: radarr sub-attribute add_to_radarr not found using None as default
| radarr sub-attribute add_to_radarr added to config
|       true (Add missing movies to Radarr)
|       false (Do not add missing movies to Radarr)
| Radarr Connection Failed
|===================================================================================================|
| Locating Image Server...
| Using S:\Plex Auto Collections\app\images for images directory
|===================================================================================================|
|
| Using cache database at S:\Plex Auto Collections\app\config.cache
| Mapping Plex Shows
| Cache | ! | local://154053                                 | No match in Plex for Westworld Chronological Order
| Processed 366 Shows
|
| Running collection update press Ctrl+C to abort at anytime
|
|===================================================================================================|
|
| Updating collection: CBS...
| Sync Mode: sync
| Processing Plex Search: studio(CBS OR CBS All Access OR CBS Television Studios)
| CBS Collection | = | 2 Broke Girls
| CBS Collection | + | Animaniacs
| CBS Collection | + | Archer
| CBS Collection | = | Back to the Future
| CBS Collection | = | The Big Bang Theory
| CBS Collection | = | The Crazy Ones
| CBS Collection | = | Ghostbusters
| CBS Collection | = | How I Met Your Mother
| CBS Collection | = | Life in Pieces
| CBS Collection | = | Limitless
| CBS Collection | = | The Mask
| CBS Collection | = | Mom
| CBS Collection | = | The Nanny
| CBS Collection | = | NCIS
| CBS Collection | = | Star Trek: Discovery
| CBS Collection | = | Star Trek: Picard
| CBS Collection | = | Superman (1988)
| CBS Collection | = | Teenage Mutant Ninja Turtles
| CBS Collection | = | Tom and Jerry
| CBS Collection | = | The Twilight Zone
| CBS Collection | = | Under the Dome
| CBS Collection | = | Young Sheldon
| Processed 22 Shows
|
| poster not found at: S:\Plex Auto Collections\app\images\CBS\poster.*
| background not found at: S:\Plex Auto Collections\app\images\CBS\background.*
|
|===================================================================================================|
PS S:\Plex Auto Collections\app>
```

**Comment by bigdork** [comment]
No one else has this issue? Weird. Well, although is reports adding shows that are already a part of the collection, it's not screwing anything up. I'll close this. *shrug*
