### ISSUE TITLE
404 on external sources

### ISSUE THREAD

**Issue by 3daystoday** [mza921/Plex-Auto-Collections#136]
Script runs fine with collections for internal plex genres for example, but as soon as I access TMDB, Traktar or IMDB it errors with a 404:

This is on 2.6.0 local, just pulled. 

Example:
```
|
| Updating collection: CBS...
| Sync Mode: append
| Config Warning: https://www.themoviedb.org/network/16 can be replaced with 16
| Processing tmdb_network: (16) Dancer in the Dark
Traceback (most recent call last):
  File "plex_auto_collections.py", line 995, in <module>
    update_from_config(config_path, plex, False)
  File "plex_auto_collections.py", line 615, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, map, filters)
  File "/opt/autocollection/app/plex_tools.py", line 151, in add_to_collection
    movies, missing = imdb_tools.tmdb_get_movies(config_path, plex, value, method)
  File "/opt/autocollection/app/imdb_tools.py", line 249, in tmdb_get_movies
    imdb_id, tmdb_id = plex_tools.alt_id_lookup(plex, item)
  File "/opt/autocollection/app/plex_tools.py", line 361, in alt_id_lookup
    with urlopen(req) as response:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

Docker version (same thing happens on 2.6.0 and 2.7.0) whatever plex url/ip I use, it wont connect and just goes back to command line after about 1 minute of trying to connect.

![image](https://user-images.githubusercontent.com/45686348/101240632-d3e54100-36f0-11eb-8374-f7f9d514b618.png)

Update: it now actually works with docker 2.7.0. Trakt trending for movies loads the library fine, shows says there are no files in the list for whatever reason.

**Comment by mza921** [comment]
The issue with Trakt trending shows has been identified.

**Comment by sean-marks** [comment]
Seems this is resolved/could be closed?
