### ISSUE TITLE
AttributeError: module 'imdb_tools' has no attribute 'imdb_get_movies'

### ISSUE THREAD

**Issue by sean-marks** [mza921/Plex-Auto-Collections#149]
Updated from 2.6 to 2.8 - getting the following error when running the first collection.

| Updating collection: IMDb Top 250...
| Sync Mode: sync
|
| Processing imdb_list: https://www.imdb.com/search/title/?groups=top_250&count=25
Traceback (most recent call last):
File "/mnt/user/appdata/Plex-Auto-Collections/app/plex_auto_collections.py", line 1026, in
update_from_config(config_path, plex, True, args.no_meta, args.no_images)
File "/mnt/user/appdata/Plex-Auto-Collections/app/plex_auto_collections.py", line 668, in update_from_config
missing, map = add_to_collection(config_path, plex, m, v, c, plex_map, map, filters)
File "/mnt/user/appdata/Plex-Auto-Collections/app/plex_tools.py", line 242, in add_to_collection
items, missing = imdb_tools.imdb_get_movies(config_path, plex, plex_map, value)
AttributeError: module 'imdb_tools' has no attribute 'imdb_get_movies'

**Comment by sean-marks** [comment]
Duplicate of 147 thus closing and adding comment there.
