### ISSUE TITLE
 AttributeError: 'AsObj' object has no attribute 'title' on radarr_tools.py, line 18

### ISSUE THREAD

**Issue by vaparr** [mza921/Plex-Auto-Collections#151]
Getting this error.. Removing the "**.format(m)**" on radarr_tools.py, line 20, fixes the issue for me.

Traceback (most recent call last):
  File "/tmp/Plex-Auto-Collections/app/radarr_tools.py", line 18, in add_to_radarr
    tmdb_title = tmovie.title
AttributeError: 'AsObj' object has no attribute 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./plex_auto_collections.py", line 1035, in <module>
    update_from_config(config_path, plex, False)
  File "./plex_auto_collections.py", line 685, in update_from_config
    add_to_radarr(config_path, missing)
  File "/tmp/Plex-Auto-Collections/app/radarr_tools.py", line 20, in add_to_radarr
    print("| --- Unable to fetch necessary TMDb information for IMDb ID {}, skipping"**.format(m)**)
NameError: name 'm' is not defined

**Comment by sean-marks** [comment]
There was a merge issue on the update to 2.8.0 last night/thus morning, he's fixing it now so I would retest after that.

**Comment by mza921** [comment]
This doesn't look like it came from the bad merge. The fix will be similar to your workaround. It's just informational, so shouldn't have any effect on radarr functionality.

**Comment by sean-marks** [comment]
Seems to be affecting myself as well --

Version: 2.8.1

Was attempting to utilize the new functionality of adding "add_to_radarr" under only a specific collection as I don't want it applied across all. Here's the configs:

collections:
Top Antidepressant Movies:
imdb_list: https://www.imdb.com/list/ls082047526/
sync_mode: sync
collection_mode: show_items
add_to_radarr: true

radarr:
url: {IP Removed}
token: {Token Removed}
quality_profile_id: 4
root_folder_path: /mnt/user/PlexMedia/movies
search_movie: false
add_to_radarr: false
version: v3

Got this error when running it:

| Adding missing movies to Radarr
Traceback (most recent call last):
File "/mnt/user/appdata/Plex-Auto-Collections/app/radarr_tools.py", line 18, in add_to_radarr
tmdb_title = tmovie.title
AttributeError: 'AsObj' object has no attribute 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/mnt/user/appdata/Plex-Auto-Collections/app/plex_auto_collections.py", line 1026, in
update_from_config(config_path, plex, True, args.no_meta, args.no_images)
File "/mnt/user/appdata/Plex-Auto-Collections/app/plex_auto_collections.py", line 685, in update_from_config
add_to_radarr(config_path, missing)
File "/mnt/user/appdata/Plex-Auto-Collections/app/radarr_tools.py", line 20, in add_to_radarr
print("| --- Unable to fetch necessary TMDb information for IMDb ID {}, skipping".format(m))
NameError: name 'm' is not defined
