### ISSUE TITLE
AttributeError: 'AsObj' object has no attribute 'title'

### ISSUE THREAD

**Issue by sean-marks** [mza921/Plex-Auto-Collections#152]
Version: 2.8.1

Was attempting to utilize the new functionality of adding "add_to_radarr" under only a specific collection as I don't want it applied across all. Here's the configs:

collections:
  Top Antidepressant Movies:
    imdb_list: https://www.imdb.com/list/ls082047526/
    sync_mode: sync
    collection_mode: show_items
    add_to_radarr: true

radarr:
  url: {IP Removed}
  token: {Token Removed}
  quality_profile_id: 4
  root_folder_path: /mnt/user/PlexMedia/movies
  search_movie: false
  add_to_radarr: false
  version: v3

Got this error when running it:

| Adding missing movies to Radarr
Traceback (most recent call last):
File "/mnt/user/appdata/Plex-Auto-Collections/app/radarr_tools.py", line 18, in add_to_radarr
tmdb_title = tmovie.title
AttributeError: 'AsObj' object has no attribute 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/mnt/user/appdata/Plex-Auto-Collections/app/plex_auto_collections.py", line 1026, in
update_from_config(config_path, plex, True, args.no_meta, args.no_images)
File "/mnt/user/appdata/Plex-Auto-Collections/app/plex_auto_collections.py", line 685, in update_from_config
add_to_radarr(config_path, missing)
File "/mnt/user/appdata/Plex-Auto-Collections/app/radarr_tools.py", line 20, in add_to_radarr
print("| --- Unable to fetch necessary TMDb information for IMDb ID {}, skipping".format(m))
NameError: name 'm' is not defined

Let me know if you need anything else from the logs or configs (or if it's just something I might've set up incorrectly?)

**Comment by sean-marks** [comment]
Closing as duplicate of 151..it did stop my script from running however.
