### ISSUE TITLE
AttributeError: 'Collections' object has no attribute 'collections'

### ISSUE THREAD

**Issue by xQsme** [mza921/Plex-Auto-Collections#157]
I had to run the config multiple times with commented blocks because it would crash after finishing some collections with the following output:
```
Traceback (most recent call last):
  File "plex_auto_collections.py", line 1035, in <module>
    update_from_config(config_path, plex, False)
  File "plex_auto_collections.py", line 695, in update_from_config
    item.removeCollection(c)
  File "C:\Users\Jabroni\AppData\Local\Programs\Python\Python38\lib\site-packages\plexapi\base.py", line 460, in removeCollection
    self._edit_tags('collection', collections, remove=True)
  File "C:\Users\Jabroni\AppData\Local\Programs\Python\Python38\lib\site-packages\plexapi\base.py", line 444, in _edit_tags
    value = getattr(self, tag + 's')
  File "C:\Users\Jabroni\AppData\Local\Programs\Python\Python38\lib\site-packages\plexapi\base.py", line 363, in __getattribute__
    value = super(PlexPartialObject, self).__getattribute__(attr)
AttributeError: 'Collections' object has no attribute 'collections'
```

My config:
```
collections:
  IMDb Top 250:
    imdb_list: https://www.imdb.com/search/title/?groups=top_250&count=25
    sync_mode: sync
    collection_mode: show_items
  Action:
    plex_search:
      genres: Action
  Adventure:
    plex_search:
      genres: Adventure
  Animation:
    plex_search:
      genres: Animation
  Comedy:
    plex_search:
      genres: Comedy
  Crime:
    plex_search:
      genres: Crime
  Drama:
    plex_search:
      genres: Drama
  Family:
    plex_search:
      genres: Family
  Fantasy:
    plex_search:
      genres: Fantasy
  Film-Noir:
    plex_search:
      genres: Film-Noir
  Horror:
    plex_search:
      genres: Horror
  Mystery:
    plex_search:
      genres: Mystery
  Sci-Fi:
    plex_search:
      genres: Sci-Fi
  Thriller:
    plex_search:
      genres: Thriller
  War:
    plex_search:
      genres: War
  Western:
    plex_search:
      genres: Western
plex: ...
```

**Comment by xQsme** [comment]
Same error when trying to generate this collection: 
```
    4k Movies:
        all: true
        filters:
            video_resolution: 2160
```

**Comment by mza921** [comment]
For your first case, `Action` and `Adventure` aren't valid genres in Plex anymore. Try using `Action/Adventure`. You can look at other valid values in if you try to filter within the GUI.

**Comment by mza921** [comment]
For your second case, looks like Plex changed the name and accepted values for their filters. I'll have to update the script for this.

**Comment by RRRuggero** [comment]
Same problem here! "AttributeError: 'Collections' object has no attribute 'collections'" ... pls mza921 !!! I'm waiting your help like a child wait for xmas! btw you and vladimir are great! thank you guys very much

**Comment by omerher** [comment]
Same problem here:
`Traceback (most recent call last):
  File "app/plex_auto_collections.py", line 1035, in <module>
    update_from_config(config_path, plex, False)
  File "app/plex_auto_collections.py", line 695, in update_from_config
    item.removeCollection(c)
  File "C:\Users\hersh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\plexapi\base.py", line 478, in removeCollection
    self._edit_tags('collection', collections, remove=True)
  File "C:\Users\hersh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\plexapi\base.py", line 462, in _edit_tags
    value = getattr(self, tag + 's')
  File "C:\Users\hersh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\plexapi\base.py", line 381, in __getattribute__
    value = super(PlexPartialObject, self).__getattribute__(attr)
AttributeError: 'Collections' object has no attribute 'collections'`
