### ISSUE TITLE
Collection Not Found still exists in build 2.8.2

### ISSUE THREAD

**Issue by paulmcclellan** [mza921/Plex-Auto-Collections#167]
Reopening, as issue 120 was closed.  Confirmed that this issue exists in 2.8.2.

Updating collection: Most Popular Kids Movies...
| Sync Mode: append
| Processing tmdb_discover: 100 movies
|            certification_country: US
|            certification.lte: G
| No Movies Found
| 100 missing movies from TMDb Discover: {'limit': 100, 'certification_country': 'US', 'certification.lte': 'G'}
| 
| Config Error: Collection Most Popular Kids Movies Not Found

**Comment by paulmcclellan** [comment]
Most Popular Kids Movies:
    tmdb_discover:
      certification_country: US
      certification.lte: G

**Comment by mza921** [comment]
Could you try using `certification: G` instead, and see if movies are returned?

**Comment by paulmcclellan** [comment]
Yep. That worked.  I was using an example from the readme file.

An error occurs when I set 'sync_mode = sync'.  I tested using it both globally, and for a single collection.  

| Updating collection: Highest Rated Movies...
| Sync Mode: sync
/mnt/user/Unraid/PlexAC2/Plex-Auto-Collections-master/app/plex_auto_collections.py:319: DeprecationWarning: Call to deprecated function or method "children", use "items" instead.
  for item in plex_collection.children:
| 
| Processing tmdb_top_rated: 100
| Processing tmdb_top_rated: 100 Items
| Highest Rated Movies Collection | + | The Shawshank Redemption
| Highest Rated Movies Collection | + | The Godfather
| Highest Rated Movies Collection | + | The Godfather: Part II
...
| Highest Rated Movies Collection | + | Vertigo
| Processed 18 Movies
| 102 missing movies from TMDb Top Rated: Top 100
| Highest Rated Movies Collection | - | Highest Rated Movies
Traceback (most recent call last):
  File "/mnt/user/Unraid/PlexAC2/Plex-Auto-Collections-master/app/plex_auto_collections.py", line 1052, in <module>
    update_from_config(config_path, plex)
  File "/mnt/user/Unraid/PlexAC2/Plex-Auto-Collections-master/app/plex_auto_collections.py", line 696, in update_from_config
    item.removeCollection(c)
  File "/usr/lib64/python3.9/site-packages/plexapi/base.py", line 475, in removeCollection
    self._edit_tags('collection', collections, remove=True)
  File "/usr/lib64/python3.9/site-packages/plexapi/base.py", line 459, in _edit_tags
    value = getattr(self, tag + 's')
  File "/usr/lib64/python3.9/site-packages/plexapi/base.py", line 378, in __getattribute__
    value = super(PlexPartialObject, self).__getattribute__(attr)
AttributeError: 'Collections' object has no attribute 'collections'

**Comment by paulmcclellan** [comment]
One other question: Does 'tmdb_popular' look for the 30 most popular movies in my library, or is it the 30 most popular in TMDB?  When I run this, it doesn't return anything (but no errors).  I have mostly old movies (pre 1960) in my library...

collections:
  Most Popular Movies:
    tmdb_popular: 30

**Comment by mza921** [comment]
`tmdb_popular` will fetch the 30 most popular in TMDb, then match that against your library.

**Comment by ramair02** [comment]
> One other question: Does 'tmdb_popular' look for the 30 most popular movies in my library, or is it the 30 most popular in TMDB? When I run this, it doesn't return anything (but no errors). I have mostly old movies (pre 1960) in my library...
> 
> collections:
> Most Popular Movies:
> tmdb_popular: 30

Per the wiki:

```
TMDb Popular (List Type)
Works with Movie and TV Show Libraries
You can build a collection using TMDb's most popular movies/shows by using tmdb_popular. The tmdb_popular attribute only supports a single integer value. The sync_mode: sync option is recommended since the list is continuously updated.

collections:
  TMDb Popular:
    tmdb_popular: 30
    sync_mode: sync
```

**Comment by paulmcclellan** [comment]
Thanks for your help!  The following works well for me.   I've been using the original version of Plex-Auto-Collections for about a year, but your enhancements are taking it to a new level!  Very pleased with the results!

  Highest Rated Action:
    tmdb_discover:
      with_genres: 28
      sort_by: vote_average.desc
      vote_count.gte: 6
      limit: 500

**Comment by ramair02** [comment]
If you want to have a collection for the most popular movies in your library, you can use Tautulli.

Here is an example from my script:
```
  Most Popular Movies (30 Days):
    sync_mode: sync
    collection_mode: show_items
    tautulli:
      list_type: popular
      list_days: 30
      list_size: 10
    sort_title: "*012"
```
