### ISSUE TITLE
TMDb Trending for TV Shows not working

### ISSUE THREAD

**Issue by BlueSkillZ99** [mza921/Plex-Auto-Collections#170]
For movies TMDb Trending works fine, for shows I am getting the following error

```
  ++TMDb Trending:
    tmdb_trending_weekly: 50
    sync_mode: sync
    sort_title: ++10TMDb Trending
```

```
| Updating collection: ++TMDb Trending...
| Sync Mode: sync
|
| Processing tmdb_trending_weekly: 50
Traceback (most recent call last):
  File "D:\Dev\Staging\Plex-Auto-Collections\app\plex_auto_collections.py", line 1035, in <module>
    update_from_config(config_path, plex, False)
  File "D:\Dev\Staging\Plex-Auto-Collections\app\plex_auto_collections.py", line 668, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, plex_map, map, filters)
  File "D:\Dev\Staging\Plex-Auto-Collections\app\plex_tools.py", line 246, in add_to_collection
    items, missing = imdb_tools.tmdb_get_shows(config_path, plex, plex_map, value, method)
  File "D:\Dev\Staging\Plex-Auto-Collections\app\imdb_tools.py", line 314, in tmdb_get_shows
    if count == amount:
UnboundLocalError: local variable 'amount' referenced before assignment
```

Based on the code used for movies (line 169 and 171), I guessed that [replacing „amount“ with „data“ in line 314 and 316](https://github.com/mza921/Plex-Auto-Collections/blob/486649a680984dc44e10c0708dc1feaa206ca3c2/app/imdb_tools.py#L314) of imdb_tools.py might fix it. As far as I can tell this works

**Comment by mza921** [comment]
Which version are you running? Can you paste the exact snippet from your config? I was able to pull down the list with:

```
collections:
  TMDb Trending:
    tmdb_trending_weekly: 50
    sync_mode: sync
```

**Comment by BlueSkillZ99** [comment]
I tested on a clean install of master I just downloaded via Github Desktop

```
  ++TMDb Trending:
    tmdb_trending_weekly: 50
    sync_mode: sync
    sort_title: ++10TMDb Trending
  ++Trakt Trending:
    trakt_trending: 50
    sync_mode: sync
    sort_title: ++11Trakt Trending
  ++TMDb Best Rated:
    tmdb_top_rated: 250
    sync_mode: sync
    sort_title: ++14TMDb Best Rated
  ++TMDb Most Popular:
    tmdb_popular: 100
    sync_mode: sync
    sort_title: ++12TMDb Most Popular

# ### Other ###
  # # +Stephen King:
    # # plex_collection: Stephen King
    # # tmdb_biography: 3027
    # # sort_title: +45Stephen King
  # # +Agatha Christie:
    # # plex_collection: Agatha Christie
    # # tmdb_biography: 47562
    # # sort_title: +45Agatha Christie
  # # ++Pandemic:
    # # plex_collection: +Pandemic
    # # sort_title: ++53Pandemic

plex:
  library: TV Shows [EN]     ###  TV Shows [EN]  TV Shows [DE]  ###
  library_type: show          ### 'movie' or 'show' ###
  token: xxxxxxxxxxxxxxxxxxxx
  url: xxxxxxxxxxxxxxxxxxxx
  sync_mode: append
radarr:
  url: xxxxxxxxxxxxxxxxxxxx
  token: xxxxxxxxxxxxxxxxxxxx
  quality_profile_id: 4
  root_folder_path: F:\Movies [EN]
  add_to_radarr: false
  search_movie: false
  version: v2
tmdb:
  apikey: xxxxxxxxxxxxxxxxxxxx
  language: en
tautulli:
  url: xxxxxxxxxxxxxxxxxxxx
  apikey: xxxxxxxxxxxxxxxxxxxx
trakt:
  client_id: xxxxxxxxxxxxxxxxxxxx
  client_secret: xxxxxxxxxxxxxxxxxxxx
  auto_refresh_token: false
  # Below is filled in automatically when the script is run
  authorization:
    access_token: xxxxxxxxxxxxxxxxxxxx
    token_type: Bearer
    expires_in: xxxxxxxxxxxxxxxxxxxx
    refresh_token: xxxxxxxxxxxxxxxxxxxx
    scope: public
    created_at: xxxxxxxxxxxxxxxxxxxx
image_server:
  poster_directory: D:\Bilder\Movie Posters\_Plex Collection Script\posters
  background_directory: ../config/backgrounds
  image_directory: ../config/images

```

```
|===================================================================================================|
|     ___  _               _         _           ___       _  _           _    _                    |
|    | _ \| | ___ __ __   /_\  _  _ | |_  ___   / __| ___ | || | ___  __ | |_ (_) ___  _ _   ___    |
|    |  _/| |/ -_)\ \ /  / _ \| || ||  _|/ _ \ | (__ / _ \| || |/ -_)/ _||  _|| |/ _ \| ' \ (_-<    |
|    |_|  |_|\___|/_\_\ /_/ \_\\_,_| \__|\___/  \___|\___/|_||_|\___|\__| \__||_|\___/|_||_|/__/    |
|                                                                                                   |
|===================================================================================================|
| Version 2.8.2
| Locating config...
| Using D:\Dev\Staging\Plex-Auto-Collections\config\config.yml as config
|===================================================================================================|
| Connecting to Plex...
| Plex Connection Successful
|===================================================================================================|
| Connecting to TMDb...
| TMDb Connection Successful
|===================================================================================================|
| Connecting to tautulli...
| tautulli Connection Successful
|===================================================================================================|
| Connecting to Trakt...
| Trakt Connection Successful
|===================================================================================================|
| Connecting to Radarr...
| Radarr Connection Successful
|===================================================================================================|
| Locating Image Server...
| Using D:\Bilder\Movie Posters\_Plex Collection Script\posters for Posters Directory
| Backgrounds Directory: ../config/backgrounds not found
| Using D:\Dev\Staging\Plex-Auto-Collections\config\images for Images Directory
|===================================================================================================|
|
| Update Collections from Config? (y/n): y
|
|===================================================================================================|
|
| Mapping Plex Shows
| Cache | ! | com.plexapp.agents.xbmcnfotv://71446?lang=xn   | Agent xbmcnfotv not supported for Money Heist
| Processed 684 Shows
|
| Running collection update press Ctrl+C to abort at anytime
|
|===================================================================================================|
|
| Updating collection: ++TMDb Trending...
| Sync Mode: sync
|
| Processing tmdb_trending_weekly: 50
Traceback (most recent call last):
  File "D:\Dev\Staging\Plex-Auto-Collections\app\plex_auto_collections.py", line 1035, in <module>
    update_from_config(config_path, plex, False)
  File "D:\Dev\Staging\Plex-Auto-Collections\app\plex_auto_collections.py", line 668, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, plex_map, map, filters)
  File "D:\Dev\Staging\Plex-Auto-Collections\app\plex_tools.py", line 246, in add_to_collection
    items, missing = imdb_tools.tmdb_get_shows(config_path, plex, plex_map, value, method)
  File "D:\Dev\Staging\Plex-Auto-Collections\app\imdb_tools.py", line 314, in tmdb_get_shows
    if count == amount:
UnboundLocalError: local variable 'amount' referenced before assignment
PS D:\Dev\Staging\Plex-Auto-Collections\app>
```

**Comment by mza921** [comment]
Confirmed. Thanks for tracking this down. I'll add the fix to the next release.

**Comment by ramair02** [comment]
Not sure if this is related to the same issue or should be in it's own thread, but I'm also having issues with TV shows for tmdb_actor and plex_search. Here are examples:

`tmdb_actor` says it only works for movies, adds nothing to collection

```
 Updating collection: Anthony Bourdain...
| Sync Mode: append
| Config Error: tmdb_actor attribute only works for movie libraries
|
| poster not found at: B:\Plex TV Shows Metadata\Anthony Bourdain.*
| poster not found at: B:\Plex Collections Metadata\Anthony Bourdain\poster.*
| background not found at: B:\Plex Collections Metadata\Anthony Bourdain\background.*
```

`plex_search` for actor says it only works for movies, adds ALL TV shows to the collection. 
```
Updating collection: Anthony Bourdain...
| Sync Mode: append
| Config Error: actor plex search attribute only works for movie libraries

| Anthony Bourdain Collection | + | 30 for 30
| Anthony Bourdain Collection | + | 30 Rock
| Anthony Bourdain Collection | + | 90 Day Fiancé
| Anthony Bourdain Collection | + | 90 Day Fiancé: Happily Ever After?
| Anthony Bourdain Collection | + | Aaahh!!! Real Monsters
| Anthony Bourdain Collection | + | The Addams Family
| Anthony Bourdain Collection | + | The Adventures of Rocky and Bullwinkle
| Anthony Bourdain Collection | + | All in the Family
| Anthony Bourdain Collection | + | American Crime Story
| Anthony Bourdain Collection | + | American Horror Story
| Anthony Bourdain Collection | + | The Americans (2013)
| Anthony Bourdain Collection | + | The Angry Beavers
| Anthony Bourdain Collection | = | Anthony Bourdain: No Reservations
| Anthony Bourdain Collection | = | Anthony Bourdain: Parts Unknown
| Anthony Bourdain Collection | + | Archie Bunker's Place
| Anthony Bourdain Collection | + | Arrested Development
| Anthony Bourdain Collection | + | Arrow
| Anthony Bourdain Collection | + | Atlanta
| Anthony Bourdain Collection | + | Autopsy: The Last Hours Of...
| Anthony Bourdain Collection | + | Awkwafina Is Nora From Queens
| Anthony Bourdain Collection | + | Band of Brothers
| Anthony Bourdain Collection | + | Barry
| Anthony Bourdain Collection | + | Baskets
| Anthony Bourdain Collection | + | Beavis and Butt-Head
| Anthony Bourdain Collection | + | Beetlejuice
| Anthony Bourdain Collection | + | Better Call Saul
| Anthony Bourdain Collection | + | Better Things
| Anthony Bourdain Collection | + | Bewitched
| Anthony Bourdain Collection | + | Big Little Lies
| Anthony Bourdain Collection | + | Billions
| Anthony Bourdain Collection | + | Black Lightning
| Anthony Bourdain Collection | + | Black Mirror
| Anthony Bourdain Collection | + | Boardwalk Empire
| Anthony Bourdain Collection | + | Bob's Burgers
| Anthony Bourdain Collection | + | Bobby's World
| Anthony Bourdain Collection | + | BoJack Horseman
| Anthony Bourdain Collection | + | Breaking Bad
| Anthony Bourdain Collection | + | Bridgerton
| Anthony Bourdain Collection | + | Broad City
| Anthony Bourdain Collection | + | The Case Against Adnan Syed
| Anthony Bourdain Collection | + | CatDog
| Anthony Bourdain Collection | + | Central Park
| Anthony Bourdain Collection | + | Chernobyl
| Anthony Bourdain Collection | + | Clarissa Explains It All
| Anthony Bourdain Collection | + | The Cleveland Show
| Anthony Bourdain Collection | + | Cobra Kai
| Anthony Bourdain Collection | + | Columbo
| Anthony Bourdain Collection | + | Comedians in Cars Getting Coffee
| Anthony Bourdain Collection | + | The Comey Rule
| Anthony Bourdain Collection | = | A Cook's Tour
| Anthony Bourdain Collection | + | Crashing (2017)
| Anthony Bourdain Collection | + | Crazy Ex-Girlfriend
| Anthony Bourdain Collection | + | Curb Your Enthusiasm
| Anthony Bourdain Collection | + | The Curse of Oak Island
| Anthony Bourdain Collection | + | Da Ali G Show
| Anthony Bourdain Collection | + | Dead to Me
| Anthony Bourdain Collection | + | The Defiant Ones
| Anthony Bourdain Collection | + | The Deuce
| Anthony Bourdain Collection | + | Dexter
| Anthony Bourdain Collection | + | Dispatches from Elsewhere
| Anthony Bourdain Collection | + | Divorce (2016)
| Anthony Bourdain Collection | + | Doug
| Anthony Bourdain Collection | + | Dragon Ball Super
| Anthony Bourdain Collection | + | Eastbound & Down
| Anthony Bourdain Collection | + | Emily in Paris
| Anthony Bourdain Collection | + | Enslaved
| Anthony Bourdain Collection | + | Entourage
| Anthony Bourdain Collection | + | Escape at Dannemora
| Anthony Bourdain Collection | + | Family Guy
| Anthony Bourdain Collection | + | Family Matters
| Anthony Bourdain Collection | + | Fargo
| Anthony Bourdain Collection | + | Fear the Walking Dead
| Anthony Bourdain Collection | + | Fernando
| Anthony Bourdain Collection | + | The Flash (2014)
| Anthony Bourdain Collection | + | The Flight Attendant
| Anthony Bourdain Collection | + | The Flintstones
| Anthony Bourdain Collection | + | Formula 1: Drive to Survive
| Anthony Bourdain Collection | + | Freaks and Geeks
| Anthony Bourdain Collection | + | The Fresh Prince of Bel-Air
| Anthony Bourdain Collection | + | Friends
| Anthony Bourdain Collection | + | Full House
| Anthony Bourdain Collection | + | Futurama
| Anthony Bourdain Collection | + | Game of Thrones
| Anthony Bourdain Collection | + | Genius (2017)
| Anthony Bourdain Collection | + | Gotham
| Anthony Bourdain Collection | + | Grace and Frankie
| Anthony Bourdain Collection | + | The Grand Tour (2016)
| Anthony Bourdain Collection | + | Great News
| Anthony Bourdain Collection | + | The Great North
| Anthony Bourdain Collection | + | The Handmaid's Tale
| Anthony Bourdain Collection | + | Happy Days
| Anthony Bourdain Collection | + | The Haunting
| Anthony Bourdain Collection | + | Heroes
| Anthony Bourdain Collection | + | Hey Arnold!
| Anthony Bourdain Collection | + | Hey Dude
| Anthony Bourdain Collection | + | Home Improvement
| Anthony Bourdain Collection | + | Homeland
| Anthony Bourdain Collection | + | The Honeymooners
| Anthony Bourdain Collection | + | Horace and Pete
| Anthony Bourdain Collection | + | House of Cards (US)
| Anthony Bourdain Collection | + | Hunters (2020)
| Anthony Bourdain Collection | + | I Dream of Jeannie
| Anthony Bourdain Collection | + | I Love Lucy
| Anthony Bourdain Collection | + | Inspector Gadget
| Anthony Bourdain Collection | + | It's Always Sunny in Philadelphia
| Anthony Bourdain Collection | + | Jane the Virgin
| Anthony Bourdain Collection | + | The Jeffersons
| Anthony Bourdain Collection | + | The Jetsons
| Anthony Bourdain Collection | + | The Jinx: The Life and Deaths of Robert Durst
| Anthony Bourdain Collection | + | Kidding
| Anthony Bourdain Collection | + | Killing Eve
| Anthony Bourdain Collection | + | The Larry Sanders Show
| Anthony Bourdain Collection | + | The Last Dance
| Anthony Bourdain Collection | + | The Last O.G.
| Anthony Bourdain Collection | + | Last Week Tonight with John Oliver
| Anthony Bourdain Collection | + | Laverne & Shirley
| Anthony Bourdain Collection | + | Law & Order
| Anthony Bourdain Collection | + | Law & Order: Special Victims Unit
| Anthony Bourdain Collection | + | Law & Order: True Crime
| Anthony Bourdain Collection | = | The Layover
| Anthony Bourdain Collection | + | The Leftovers
| Anthony Bourdain Collection | + | Looney Tunes
| Anthony Bourdain Collection | + | Looney Tunes Cartoons
| Anthony Bourdain Collection | + | The Looney Tunes Show
| Anthony Bourdain Collection | + | The Loudest Voice
| Anthony Bourdain Collection | + | Louie (2010)
| Anthony Bourdain Collection | + | Love & Hip Hop New York
| Anthony Bourdain Collection | + | Lovecraft Country
| Anthony Bourdain Collection | + | Lucifer
| Anthony Bourdain Collection | + | Lucky Louie
| Anthony Bourdain Collection | + | Mad Men
| Anthony Bourdain Collection | + | Making a Murderer
| Anthony Bourdain Collection | + | Making It
| Anthony Bourdain Collection | + | The Man in the High Castle
| Anthony Bourdain Collection | + | The Mandalorian
| Anthony Bourdain Collection | + | Maniac (2018)
| Anthony Bourdain Collection | + | Marvel's Agents of S.H.I.E.L.D.
| Anthony Bourdain Collection | + | Marvel's Cloak & Dagger
| Anthony Bourdain Collection | + | Marvel's Daredevil
| Anthony Bourdain Collection | + | Marvel's Jessica Jones
| Anthony Bourdain Collection | + | Marvel's Runaways
| Anthony Bourdain Collection | + | The Marvelous Mrs. Maisel
| Anthony Bourdain Collection | + | The Mary Tyler Moore Show
| Anthony Bourdain Collection | + | Master of None
| Anthony Bourdain Collection | + | Max Verstappen: Whatever It Takes
| Anthony Bourdain Collection | + | MINDHUNTER
| Anthony Bourdain Collection | + | Mister Rogers' Neighborhood
| Anthony Bourdain Collection | + | Mork & Mindy
| Anthony Bourdain Collection | + | The Morning Show
| Anthony Bourdain Collection | + | Mr. Robot
| Anthony Bourdain Collection | + | The Munsters
| Anthony Bourdain Collection | + | The Murder of Laci Peterson
| Anthony Bourdain Collection | + | Mythic Quest: Raven's Banquet
| Anthony Bourdain Collection | + | Narcos
| Anthony Bourdain Collection | + | The New Yankee Workshop
| Anthony Bourdain Collection | + | The Newsroom (2012)
| Anthony Bourdain Collection | + | The Night Of
| Anthony Bourdain Collection | + | The Office
| Anthony Bourdain Collection | + | The Office (US)
| Anthony Bourdain Collection | + | One Strange Rock
| Anthony Bourdain Collection | + | Orange Is the New Black
| Anthony Bourdain Collection | + | Oz
| Anthony Bourdain Collection | + | Ozark
| Anthony Bourdain Collection | + | Parks and Recreation
| Anthony Bourdain Collection | + | The Pink Panther
| Anthony Bourdain Collection | + | Popeye
| Anthony Bourdain Collection | + | The Queen's Gambit
| Anthony Bourdain Collection | + | Ramy
| Anthony Bourdain Collection | + | Ratched
| Anthony Bourdain Collection | + | The Real Ghostbusters
| Anthony Bourdain Collection | + | The Ren and Stimpy Show
| Anthony Bourdain Collection | + | The Richard Pryor Show
| Anthony Bourdain Collection | + | Rick and Morty
| Anthony Bourdain Collection | + | The Righteous Gemstones
| Anthony Bourdain Collection | + | Riverdale
| Anthony Bourdain Collection | + | Rocko's Modern Life
| Anthony Bourdain Collection | + | The Rocky and Bullwinkle Show
| Anthony Bourdain Collection | + | Rugrats
| Anthony Bourdain Collection | + | Salute Your Shorts
| Anthony Bourdain Collection | + | Santa Clarita Diet
| Anthony Bourdain Collection | + | Schitt's Creek
| Anthony Bourdain Collection | + | The Scooby-Doo Show
| Anthony Bourdain Collection | + | Scooby-Doo, Where Are You!
| Anthony Bourdain Collection | + | See
| Anthony Bourdain Collection | + | Seinfeld
| Anthony Bourdain Collection | + | Shameless (US)
| Anthony Bourdain Collection | + | Shark Tank
| Anthony Bourdain Collection | + | Sharp Objects
| Anthony Bourdain Collection | + | The Shield
| Anthony Bourdain Collection | + | Silicon Valley
| Anthony Bourdain Collection | + | The Simpsons
| Anthony Bourdain Collection | + | The Sinner
| Anthony Bourdain Collection | + | Sons of Anarchy
| Anthony Bourdain Collection | + | The Sopranos
| Anthony Bourdain Collection | + | South Park
| Anthony Bourdain Collection | + | SpongeBob SquarePants
| Anthony Bourdain Collection | + | Stranger Things
| Anthony Bourdain Collection | + | Succession
| Anthony Bourdain Collection | + | Supergirl
| Anthony Bourdain Collection | + | Surviving R. Kelly
| Anthony Bourdain Collection | + | Tales from the Crypt
| Anthony Bourdain Collection | + | Taxi
| Anthony Bourdain Collection | + | Ted Lasso
| Anthony Bourdain Collection | + | Teenage Mutant Ninja Turtles
| Anthony Bourdain Collection | + | This Old House
| Anthony Bourdain Collection | + | The Three Stooges
| Anthony Bourdain Collection | + | Tom and Jerry
| Anthony Bourdain Collection | + | True Blood
| Anthony Bourdain Collection | + | True Detective
| Anthony Bourdain Collection | + | The Twilight Zone
| Anthony Bourdain Collection | + | The Twilight Zone (2019)
| Anthony Bourdain Collection | + | Twin Peaks
| Anthony Bourdain Collection | + | Unbreakable Kimmy Schmidt
| Anthony Bourdain Collection | + | Undeclared
| Anthony Bourdain Collection | + | Veep
| Anthony Bourdain Collection | + | Vice Principals
| Anthony Bourdain Collection | + | The Walking Dead
| Anthony Bourdain Collection | + | Watchmen
| Anthony Bourdain Collection | + | Weeds
| Anthony Bourdain Collection | + | The West Wing
| Anthony Bourdain Collection | + | Westworld
| Anthony Bourdain Collection | + | The Wire
| Anthony Bourdain Collection | + | Workaholics
| Anthony Bourdain Collection | + | Yellowstone (2018)
| Anthony Bourdain Collection | + | Your Honor (US)
| Anthony Bourdain Collection | + | The Zen Diaries of Garry Shandling
| Processed 226 Shows
|
| poster not found at: B:\Plex TV Shows Metadata\Anthony Bourdain.*
| poster not found at: B:\Plex Collections Metadata\Anthony Bourdain\poster.*
| background not found at: B:\Plex Collections Metadata\Anthony Bourdain\background.*
```

**Comment by BlueSkillZ99** [comment]
tmdb_actor issue is probably feature request. Also the readme specifies that it is only available for movies

I recall that there was a reported issue regarding plex_search. But you can use filters instead

```
  +Will Smith:
    all: true
    filters:
      actor: Will Smith
    tmdb_biography: 2888
```

**Comment by mza921** [comment]
@ramair02 Can you please post your relevant collection config in #172?

**Comment by ramair02** [comment]
@mza921 Yes, just added it. Thanks.
