### ISSUE TITLE
tmovie referenced before assignment

### ISSUE THREAD

**Issue by cranky-coder** [mza921/Plex-Auto-Collections#171]
Running latest docker build.  Connection to plex appears ok.  So far just trying to get it started, have trakt, radar, tmdb sections commented out as I would like to see what it does with just some basic plex stuff.   Looks like it's trying to do an initial scan/map of my movies, get's to the second one and fails.

|===================================================================================================|,
|     ___  _               _         _           ___       _  _           _    _                    |,
|    | _ \| | ___ __ __   /_\  _  _ | |_  ___   / __| ___ | || | ___  __ | |_ (_) ___  _ _   ___    |,
|    |  _/| |/ -_)\ \ /  / _ \| || ||  _|/ _ \ | (__ / _ \| || |/ -_)/ _||  _|| |/ _ \| ' \ (_-<    |,
|    |_|  |_|\___|/_\_\ /_/ \_\\_,_| \__|\___/  \___|\___/|_||_|\___|\__| \__||_|\___/|_||_|/__/    |,
|                                                                                                   |,
|===================================================================================================|,
| Version 2.8.2,
| Locating config...,
| Using /config/config.yml as config,
|===================================================================================================|,
| Connecting to Plex...,
| Plex Connection Successful,
|===================================================================================================|,
| tmdb attribute not found,
|===================================================================================================|,
| Connecting to tautulli...,
| tautulli Connection Successful,
|===================================================================================================|,
| trakt attribute not found,
|===================================================================================================|,
| radarr attribute not found,
|===================================================================================================|,
| image_server attribute not found,
|===================================================================================================|,
|,
| Mapping Plex Movies,
| Processing: 1/1567 2 Fast 2 Furious
| Processing: 2/1567 3 Days to Kill  
,
Traceback (most recent call last):,
  File "/app/plex_auto_collections.py", line 1026, in <module>,
    update_from_config(config_path, plex, True, args.no_meta, args.no_images),
  File "/app/plex_auto_collections.py", line 120, in update_from_config,
    plex_map = get_map(config_path, plex),
  File "/app/plex_tools.py", line 138, in get_map,
    tmdbapi = tmovie.details(check_id),
UnboundLocalError: local variable 'tmovie' referenced before assignment,

**Comment by cranky-coder** [comment]
cancel.  Looks like even just mapping to tmdb collections needed the API key set.  So that was my fault
