### ISSUE TITLE
Unicode errors - script crashes.

### ISSUE THREAD

**Issue by mescon** [mza921/Plex-Auto-Collections#198]
Hey, thanks for a wonderful tool! Very much appreciated!

I'm trying to match my library called ``Movies (HD)`` to this imdb list: https://www.imdb.com/list/ls024106029

My config.yml is:
```
collections:
  Criterion Collection:
    imdb_list: https://www.imdb.com/list/ls024106029
plex:
  library: Movies (HD)
  library_type: movie
  token: redacted
  url: http://127.0.0.1:32400
  sync_mode: append
```

And here is the output:

```
| GUID map | + | plex://movie/5d776824e6d55c002040ae63  | tt0017136 | Metropolis (1927)
| GUID map | + | plex://movie/5d776824e6d55c002040ae63  | 19        | Metropolis (1927)
| GUID map | + | plex://movie/5d776bb9ad5437001f7a820a  | tt4560436 | Mile 22 (2018)
| GUID map | + | plex://movie/5d776bb9ad5437001f7a820a  | 347375    | Mile 22 (2018)
| GUID map | + | plex://movie/5d776a417a53e9001e6ff57a  | tt2293640 | Minions (2015)
| GUID map | + | plex://movie/5d776a417a53e9001e6ff57a  | 211672    | Minions (2015)
| GUID map | + | plex://movie/5d7768a00ea56a001e2a7fd0  | tt1210166 | Moneyball (2011)
| GUID map | + | plex://movie/5d7768a00ea56a001e2a7fd0  | 60308     | Moneyball (2011)
| GUID map | + | plex://movie/5d776c547a53e9001e74056e  | tt5869350 | Morran & Tobias: Godsend (2016)
| GUID map | + | plex://movie/5d776c547a53e9001e74056e  | 404789    | Morran & Tobias: Godsend (2016)
| GUID map | + | plex://movie/5d77689c9ab54400214e8839  | tt1396218 | Mr. Popper's Penguins (2011)
| GUID map | + | plex://movie/5d77689c9ab54400214e8839  | 58224     | Mr. Popper's Penguins (2011)
Traceback (most recent call last):
  File "plex_auto_collections.py", line 1035, in <module>
    update_from_config(config_path, plex, False)
  File "plex_auto_collections.py", line 120, in update_from_config
    plex_map = get_map(config_path, plex)
  File "/opt/Plex-Auto-Collections/app/plex_tools.py", line 90, in get_map
    update_guid_map_from_db(config_path, plex)
  File "/opt/Plex-Auto-Collections/app/plex_tools.py", line 429, in update_guid_map_from_db
    print("| GUID map | + | {:38} | {:<9} | {} ({})".format(row['guid'], urlparse(row['tag']).netloc, row['title'], row['year']))
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 89: ordinal not in range(128)
```

Googling the error (last line) gave me this: https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20

It's a big list (1354 movies), and I've got maybe 4000 movies in total in my library to search through...

I'm no Python-guy myself, but perhaps I'm doing something wrong in my setup, or is this an actual bug?
Either way, I would very much appreciate any feedback on this!

Thanks!

**Comment by mescon** [comment]
I think it might have been that $LANG and $LC_ALL was set to ``C``. Changed it to ``en_US.utf8`` and now I'm on to another error instead, but I'd say this particular error was on my end. Closing.
