### ISSUE TITLE
Adding TV by "imdb_show" crashes script

### ISSUE THREAD

**Issue by bigdork** [mza921/Plex-Auto-Collections#199]
Just updated to 2.9.0 (including pip install --upgrade -r requirements.txt) and now the use of "imdb_show" crashes the script.

I have tried this show ID and URL:
```
collections:
  test_imdb_show:
    tmdb_show:
      - 70391
      - 78881
```
```
|===================================================================================================|
| Version 2.9.0
| Locating config...
| Using /opt/scripts/Plex-Auto-Collections/config/config.tv.networks.yml as config
|===================================================================================================|
| Connecting to Plex...
| Plex Connection Successful
|===================================================================================================|
| Connecting to TMDb...
| TMDb Connection Successful
|===================================================================================================|
| Connecting to tautulli...
| tautulli Connection Successful
|===================================================================================================|
| Connecting to Trakt...
| Trakt Connection Successful
|===================================================================================================|
| radarr attribute not found
|===================================================================================================|
| image_server attribute not found
|===================================================================================================|
|
| Mapping Plex Shows
| Processed 7769 Shows
|
| Running collection update press Ctrl+C to abort at anytime
|
|===================================================================================================|
|
| Updating collection: Test imdb_show...
| Sync Mode: sync
Traceback (most recent call last):
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 1026, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 498, in update_from_config
    methods.append(get_method_pair_tmdb(method_name, collections[c][m], "TMDb Show ID"))
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 73, in get_method_pair_tmdb
    tmdb_get_metadata(config_path, id, "overview")
  File "/opt/scripts/Plex-Auto-Collections/app/imdb_tools.py", line 379, in tmdb_get_metadata
    meta = collection.details(tmdb_id).overview
  File "/home/pg/.local/lib/python3.6/site-packages/tmdbv3api/objs/collection.py", line 18, in details
    return AsObj(**self._call(self._urls["details"] % str(collection_id), ""))
  File "/home/pg/.local/lib/python3.6/site-packages/tmdbv3api/as_obj.py", line 9, in __init__
    raise TMDbException(entries["status_message"])
tmdbv3api.exceptions.TMDbException: The resource you requested could not be found.
```
The results with URL are similar, with a warning about using the show ID instead:
```
  Test imdb_show:
    tmdb_show:
      - https://www.themoviedb.org/tv/70391-philip-k-dick-s-electric-dreams
      - https://www.themoviedb.org/tv/78881-picnic-at-hanging-rock
```
```
| Updating collection: test_imdb_show...
| Sync Mode: sync
| Config Warning: https://www.themoviedb.org/tv/70391-philip-k-dick-s-electric-dreams can be replaced with 70391
Traceback (most recent call last):
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 1026, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 498, in update_from_config
    methods.append(get_method_pair_tmdb(method_name, collections[c][m], "TMDb Show ID"))
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 73, in get_method_pair_tmdb
    tmdb_get_metadata(config_path, id, "overview")
  File "/opt/scripts/Plex-Auto-Collections/app/imdb_tools.py", line 379, in tmdb_get_metadata
    meta = collection.details(tmdb_id).overview
  File "/home/pg/.local/lib/python3.6/site-packages/tmdbv3api/objs/collection.py", line 18, in details
    return AsObj(**self._call(self._urls["details"] % str(collection_id), ""))
  File "/home/pg/.local/lib/python3.6/site-packages/tmdbv3api/as_obj.py", line 9, in __init__
    raise TMDbException(entries["status_message"])
tmdbv3api.exceptions.TMDbException: The resource you requested could not be found.
```
I have also tried many different TVDB IDs (1434 Family Guy, for example), with the same issues.

**Comment by mechanimal82** [comment]
Just installed this myself and come across the same issue....

```
| Cache | ! | plex://movie/5f84a6abe5f2cc003d2b2747          | Unable to map TMDb/IMDb ID for Max Winslow and The House of Secrets
| Cache | ! | plex://movie/5d776cd596b655001fe3ab90          | Unable to map TMDb/IMDb ID for Photograph
| Cache | ! | plex://movie/5d7768325af944001f1f9432          | Unable to map TMDb/IMDb ID for Police Academy
| Cache | ! | plex://movie/5f86673215674b00405afcbf          | Unable to map TMDb/IMDb ID for Secrets of the Saqqara Tomb
| Cache | ! | plex://movie/5d776cd3fb0d55001f59264c          | Unable to map TMDb/IMDb ID for The Silence
| Processing: 4532/5283 Star Wars Episode IX-The Rise of Skywalker: Digital Extras
Traceback (most recent call last):
  File "plex_auto_collections.py", line 1035, in <module>
    update_from_config(config_path, plex, False)
  File "plex_auto_collections.py", line 120, in update_from_config
    plex_map = get_map(config_path, plex)
  File "/opt/plex-auto-collections/plex_tools.py", line 145, in get_map
    tmdbapi = tmovie.details(check_id)
  File "/usr/local/lib/python3.8/dist-packages/tmdbv3api/objs/movie.py", line 49, in details
    return AsObj(
  File "/usr/local/lib/python3.8/dist-packages/tmdbv3api/as_obj.py", line 9, in __init__
    raise TMDbException(entries["status_message"])
tmdbv3api.exceptions.TMDbException: The resource you requested could not be found.

```
