### ISSUE TITLE
Using multiple tmdb_id / tmdb_movie entries in a collection can causes the script to crash

### ISSUE THREAD

**Issue by drpeppershaker** [mza921/Plex-Auto-Collections#200]
EDIT: this was working with version 2.7, but after updating to current version a bunch of stuff broke.

I've tried it with tmdb_id: 2661, tmdb_movie: 2661, tmdb_id: https://www.themoviedb.org/movie/2661-batman, tmdb_movie: https://www.themoviedb.org/movie/2661-batman

And they all crash.

Snippet from config file:
```
  Batman Collection:
    tmdb_collection: 120794
    tmdb_movie: 2661
    collection_order: release
    collection_mode: hide_items
```

Result:
```
| Updating collection: Batman Collection...
| Sync Mode: append
Traceback (most recent call last):
File "/mnt/user/appdata/Plex-Auto-Collections/app/plex_auto_collections.py", line 1026, in
update_from_config(config_path, plex, True, args.no_meta, args.no_images)
File "/mnt/user/appdata/Plex-Auto-Collections/app/plex_auto_collections.py", line 494, in update_from_config
methods.append(get_method_pair_tmdb(method_name, collections[c][m], "TMDb Movie ID"))
File "/mnt/user/appdata/Plex-Auto-Collections/app/plex_auto_collections.py", line 73, in get_method_pair_tmdb
tmdb_get_metadata(config_path, id, "overview")
File "/mnt/user/appdata/Plex-Auto-Collections/app/imdb_tools.py", line 379, in tmdb_get_metadata
meta = collection.details(tmdb_id).overview
File "/usr/lib64/python3.9/site-packages/tmdbv3api/objs/collection.py", line 18, in details
return AsObj(**self._call(self._urls["details"] % str(collection_id), ""))
File "/usr/lib64/python3.9/site-packages/tmdbv3api/as_obj.py", line 9, in __init__
raise TMDbException(entries["status_message"])
tmdbv3api.exceptions.TMDbException: The resource you requested could not be found.
```

**Comment by drpeppershaker** [comment]
Also crashes with the following:

tmdb:456740
https://www.themoviedb.org/movie/456740-hellboy

config snippet: 
```
  Hellboy Collection:
    collection_mode: hide_items
    tmdb_id: 17235
    tmdb_movie: 456740
    collection_order: release
```

tmdb_movie: 476669
https://www.themoviedb.org/movie/476669-the-king-s-man

```
  The Kingsman Collection:
    sort_title: Kingsman Collection
    collection_mode: hide_items
    tmdb_id: 391860
    tmdb_movie: 476669
    collection_order: release
```

This also causes the script to crash:
```
  The Man With No Name Collection:
    sort_title: Man With No Name Collection
    collection_mode: hide_items
    tmdb_movie: 
      - 391
      - 938
      - 429
    collection_order: release
```

Another one:
```
  The Matrix Collection:
    sort_title: Matrix
    collection_mode: hide_items
    tmdb_id: 2344, 55931
    #tmdb_movie: 55931
    collection_order: release
```

**Comment by drpeppershaker** [comment]
This leads me to believe that having multiple tmdb IDs in a collection can cause the script to fail.
However, I have noticed that my Addams Family collection succeeds. 

```
  Addams Family Collection:
    collection_mode: hide_items
    tmdb_id: 11716
    tmdb_collection: 750822
    collection_order: release
```

**Comment by tehniemer** [comment]
I'm having similar crashing issues after the update.

**Comment by drpeppershaker** [comment]
@tehniemer 
Rolling back to **tmdbv3api==1.7.1** seems to have fixed the issues for me--even while keep plex-auto-collections at v2.9

Not sure if there's any dependency on 1.7.4 that I haven't bumped into, but I'm going to keep tmdbv3api==1.7.1 until this issue is resolved

**Comment by tehniemer** [comment]
@drpeppershaker Thanks for the info, but I'm not totally sure how to do that with the Docker container.

**Comment by xFlawless11x** [comment]
Having the same error - I dropped it to 1.7.1 but doesn't seem to have resolved it
