### ISSUE TITLE
KeyError causing script to crash when adding to radarr

### ISSUE THREAD

**Issue by doctarrwho** [mza921/Plex-Auto-Collections#202]
Seeing the script crash in the last few days. It used to work fine and nothing has changed in the config. The issue is easy to reproduce by adding the trakt trending list. 

```
| Updating collection: * Trending on Trakt...
| Sync Mode: sync
|
| Processing trakt_trending: 25
| 25 Movies found on Trakt
| * Trending on Trakt Collection | = | The Little Things
| * Trending on Trakt Collection | = | Palmer
| * Trending on Trakt Collection | = | Wonder Woman 1984
| * Trending on Trakt Collection | = | News of the World
| * Trending on Trakt Collection | = | Tenet
| * Trending on Trakt Collection | = | Breach
| * Trending on Trakt Collection | = | Godzilla: King of the Monsters
| * Trending on Trakt Collection | = | Captain America: The Winter Soldier
| * Trending on Trakt Collection | = | Avengers: Endgame
| * Trending on Trakt Collection | = | Greenland
| * Trending on Trakt Collection | = | Promising Young Woman
| * Trending on Trakt Collection | = | The Matrix
| * Trending on Trakt Collection | = | Iron Man 2
| * Trending on Trakt Collection | = | Harry Potter and the Chamber of Secrets
| * Trending on Trakt Collection | = | Captain Marvel
| * Trending on Trakt Collection | = | Spider-Man: Far from Home
| * Trending on Trakt Collection | = | Bad Boys for Life
| * Trending on Trakt Collection | = | Shadow in the Cloud
| * Trending on Trakt Collection | = | Synchronic
| * Trending on Trakt Collection | + | Captain America: Civil War
| * Trending on Trakt Collection | = | The Lord of the Rings: The Return of the King
| * Trending on Trakt Collection | = | Harry Potter and the Sorcerer's Stone
| Processed 22 Movies
| 3 missing movies from Trakt Trending: Top 25
| Adding missing movies to Radarr
Traceback (most recent call last):
File "/app/plex_auto_collections.py", line 1026, in <module>
update_from_config(config_path, plex, True, args.no_meta, args.no_images)
File "/app/plex_auto_collections.py", line 685, in update_from_config
add_to_radarr(config_path, missing)
File "/app/radarr_tools.py", line 71, in add_to_radarr
print("| --- {}: {} {}".format(tmdb_title, response.json()[0]['errorMessage'], response.status_code))
KeyError: 0
```

Here's the config for the collection that is failing.

```yaml
    "* Trending on Trakt":
        sort_title: "*100"
        trakt_trending: 25
        sync_mode: sync
        add_to_radarr: true
        trakt_list:
            - https://trakt.tv/users/giladg/lists/top-10-movies-of-the-week?sort=added,asc
```
This is the code throwing the exception:

```python
        if response.status_code < 400:
            print("| +++ {}: Added to Radarr".format(tmdb_title))
        else:
            print("| --- {}: {} {}".format(tmdb_title, response.json()[0]['errorMessage'], response.status_code))
```

Radarr logs show the following two events when the exception occurs.

```
Radarr.Http.REST.BadRequestException: BadRequest: Invalid request body. The JSON value could not be converted to System.Int32. Path: $.tmdbid | LineNumber: 0 | BytePositionInLine: 74.
   at Radarr.Http.REST.RestModule`1.ReadResourceFromRequest(Boolean skipValidate, Boolean skipSharedValidate) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 253
   at Radarr.Http.REST.RestModule`1.<set_CreateResource>b__43_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 206
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
```

```
Invalid request Validation failed: 
 -- Path: Invalid Path
 -- RootFolderPath: Invalid Path
 -- Title: 'Title' must not be empty.
 -- TmdbId: 'Tmdb Id' must not be empty.
```

Setting add_to_radarr to false for this collection does bypass the issue for the time being.

**Comment by vaparr** [comment]
I’m seeing the same issue on a different trakt collection

**Comment by nicodog11** [comment]
I am having the same issue

**Comment by ramair02** [comment]
I'm having a *similar* issue when the script his the Tautulli Most Popular collection.

```
 Updating collection: Most Popular Movies (30 Days)...
| Sync Mode: sync
|
| Processing tautulli: {'list_type': 'popular', 'list_days': 30, 'list_size': 10, 'list_buffer': 10}
Traceback (most recent call last):
  File "B:\Tautulli Scripts\PAC-2.8.2\Plex-Auto-Collections-movies\app\plex_auto_collections.py", line 1035, in <module>
    update_from_config(config_path, plex, False)
  File "B:\Tautulli Scripts\PAC-2.8.2\Plex-Auto-Collections-movies\app\plex_auto_collections.py", line 668, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, plex_map, map, filters)
  File "B:\Tautulli Scripts\PAC-2.8.2\Plex-Auto-Collections-movies\app\plex_tools.py", line 265, in add_to_collection
    items, missing = imdb_tools.get_tautulli(config_path, plex, value)
  File "B:\Tautulli Scripts\PAC-2.8.2\Plex-Auto-Collections-movies\app\imdb_tools.py", line 250, in get_tautulli
    matched.append(plex.Library.fetchItem(item['rating_key']))
  File "C:\Users\jonat\AppData\Local\Programs\Python\Python39\lib\site-packages\plexapi\base.py", line 139, in fetchItem
    for elem in self._server.query(ekey):
  File "C:\Users\jonat\AppData\Local\Programs\Python\Python39\lib\site-packages\plexapi\server.py", line 448, in query
    raise NotFound(message)
plexapi.exceptions.NotFound: (404) not_found; http://10.0.0.25:32400/library/metadata/300682 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
```

Config hasn't changed, but here it is for good measure.

```
  Most Popular Movies (30 Days):
    sync_mode: sync
    collection_mode: show_items
    tautulli:
      list_type: popular
      list_days: 30
      list_size: 10
      list_buffer: 10
    sort_title: "*013"
```
