### ISSUE TITLE
tmdbv3api issue

### ISSUE THREAD

**Issue by jalarab** [mza921/Plex-Auto-Collections#205]
When the script is mapping plex movies I receive this error with the first movie with tmdb agent:

| Processing: 1019/12530 The Backyardigans: Cave Party
Traceback (most recent call last):
  File "plex_auto_collections.py", line 1026, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "plex_auto_collections.py", line 120, in update_from_config
    plex_map = get_map(config_path, plex)
  File "F:\Plex-Auto-Collections\app\plex_tools.py", line 145, in get_map
    tmdbapi = tmovie.details(check_id)
  File "C:\Python38\lib\site-packages\tmdbv3api\objs\movie.py", line 49, in details
    return AsObj(
  File "C:\Python38\lib\site-packages\tmdbv3api\as_obj.py", line 9, in __init__
    raise TMDbException(entries["status_message"])
tmdbv3api.exceptions.TMDbException: The resource you requested could not be found.

My system:
Windows 10
Python 3.8.2
Plex:Auto_Collection: 2.9
PlexAPI==4.2.0
tmdbv3api==1.7.4
Last PMS

**Comment by jalarab** [comment]
Rolling back to tmdbv3api==1.7.1 solves the problem

**Comment by romprod** [comment]
> Rolling back to tmdbv3api==1.7.1 solves the problem

I'm having the same issue, can you explain how you rolled back to 1.7.1 please?

**Comment by jalarab** [comment]
pip install tmdbv3api==1.7.1
