### ISSUE TITLE
Error with genre

### ISSUE THREAD

**Issue by zhdenny** [mza921/Plex-Auto-Collections#214]
Running latest version. Not sure what is going here.
```
Traceback (most recent call last):
  File "/opt/Plex-Auto-Collections/app/plex_auto_collections.py", line 1026, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "/opt/Plex-Auto-Collections/app/plex_auto_collections.py", line 668, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, plex_map, map, filters)
  File "/opt/Plex-Auto-Collections/app/plex_tools.py", line 242, in add_to_collection
    items = plex.Library.search(**search_terms)
  File "/home/beast/.local/lib/python3.8/site-packages/plexapi/library.py", line 669, in search
    args[category] = self._cleanSearchFilter(category, value, libtype)
  File "/home/beast/.local/lib/python3.8/site-packages/plexapi/library.py", line 717, in _cleanSearchFilter
    raise BadRequest('Unknown filter category: %s' % category)
plexapi.exceptions.BadRequest: Unknown filter category: genre
```

```
collections:
    Animated Movies:
        plex_search:
            genre: Animation
        sort_title: '*102'
        collection_order: alpha
```

Plex Version 1.22.0.4145
Latest git pull origin master 3/6/2021 for Plex-Auto-Collections

**Comment by meisnate12** [comment]
duplicate of #212 it's because you're using the Beta Branch of PMS and they changed how their API functions
