### ISSUE TITLE
TV Collection errors out

### ISSUE THREAD

**Issue by vitadome** [mza921/Plex-Auto-Collections#215]
Hi,
Trying to create a collection in TV Library which keeps erroring out.  Would anyone know how to fix this issue?

| Processing: 1143/8923 Brigada Costa Del Sol
Traceback (most recent call last):
  File "plex_auto_collections.py", line 1035, in <module>
    update_from_config(config_path, plex, False)
  File "plex_auto_collections.py", line 120, in update_from_config
    plex_map = get_map(config_path, plex)
  File "C:\23317a\app\plex_tools.py", line 156, in get_map
    key_id = imdb_tools.tmdb_get_tvdb(config_path, check_id)
  File "C:\23317a\app\imdb_tools.py", line 79, in tmdb_get_tvdb
    search = show.external_ids(tmdb_id)['tvdb_id']
  File "C:\Users\vitdom01\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tmdbv3api\objs\tv.py", line 148, in external_ids
    return self._get_obj(
  File "C:\Users\vitdom01\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tmdbv3api\tmdb.py", line 101, in _get_obj
    raise TMDbException(result["status_message"])
tmdbv3api.exceptions.TMDbException: The resource you requested could not be found.

**Comment by meisnate12** [comment]
can you post your meta.log file and your collection config

**Comment by vitadome** [comment]
Attached config but unsure where to find meta.log

[config_test.zip](https://github.com/mza921/Plex-Auto-Collections/files/6127365/config_test.zip)

**Comment by meisnate12** [comment]
lol im in the wrong repo my bad i thought i was in mine haha this is a dupe of #205 here

**Comment by vitadome** [comment]
LOL.  I did manage to rollback as the other issue suggested.  However, I'm still getting the same error.

  Attempting uninstall: tmdbv3api
    Found existing installation: tmdbv3api 1.7.4
    Uninstalling tmdbv3api-1.7.4:
      Successfully uninstalled tmdbv3api-1.7.4
Successfully installed tmdbv3api-1.7.1

**Comment by vitadome** [comment]
| Processing: 1143/8923 Brigada Costa Del Sol
Traceback (most recent call last):
  File "plex_auto_collections.py", line 1035, in <module>
    update_from_config(config_path, plex, False)
  File "plex_auto_collections.py", line 120, in update_from_config
    plex_map = get_map(config_path, plex)
  File "C:\23317a\app\plex_tools.py", line 156, in get_map
    key_id = imdb_tools.tmdb_get_tvdb(config_path, check_id)
  File "C:\23317a\app\imdb_tools.py", line 79, in tmdb_get_tvdb
    search = show.external_ids(tmdb_id)['tvdb_id']
  File "C:\Users\vitdom01\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tmdbv3api\objs\tv.py", line 148, in external_ids
    return self._get_obj(
  File "C:\Users\vitdom01\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tmdbv3api\tmdb.py", line 101, in _get_obj
    raise Exception(result["status_message"])
Exception: The resource you requested could not be found.

**Comment by meisnate12** [comment]
that ones a little different and unfortunately isn't going to go away unless that Exception is caught and handled

**Comment by vitadome** [comment]
OK, I hope it's caught and handled someday. :) I appreciate your help!  Thank you!

**Comment by meisnate12** [comment]
no problem but check out my program in my profile you might like it too
