### ISSUE TITLE
Recently moved Windows to Unraid, Trouble getting the script to run

### ISSUE THREAD

**Issue by ramair02** [mza921/Plex-Auto-Collections#218]
I had a working Plex-Auto-Collections script on Windows. I recently moved to Unraid and am trying to get it working through User Scripts. 

The script found all of my movies and mapped them, great!

But the script fails after that. Here is the output:

```
| Processed 2679 Movies
|
| Running collection update press Ctrl+C to abort at anytime
|
|===================================================================================================|
|
| Updating collection: 30s Movies...
| Sync Mode: append
| Processing Plex Search: decade(1930)
Traceback (most recent call last):
File "/mnt/user/appdata/plexautocollections/plexauto-master/app/plex_auto_collections.py", line 1026, in
update_from_config(config_path, plex, True, args.no_meta, args.no_images)
File "/mnt/user/appdata/plexautocollections/plexauto-master/app/plex_auto_collections.py", line 668, in update_from_config
missing, map = add_to_collection(config_path, plex, m, v, c, plex_map, map, filters)
File "/mnt/user/appdata/plexautocollections/plexauto-master/app/plex_tools.py", line 242, in add_to_collection
items = plex.Library.search(**search_terms)
File "/usr/lib64/python3.9/site-packages/plexapi/library.py", line 669, in search
args[category] = self._cleanSearchFilter(category, value, libtype)
File "/usr/lib64/python3.9/site-packages/plexapi/library.py", line 717, in _cleanSearchFilter
raise BadRequest('Unknown filter category: %s' % category)
plexapi.exceptions.BadRequest: Unknown filter category: decade
```

I'm not sure where to start with troubleshooting. If it helps to know more about how I have the script setup, please let me know. Thanks!

**Comment by meisnate12** [comment]
this is a duplicate issue #212 its because plex changed an API endpoint you can find more info in the other thread

**Comment by ramair02** [comment]
ah thank you and sorry for the duplication
