### ISSUE TITLE
Continually getting traceback error.

### ISSUE THREAD

**Issue by spicerackk** [mza921/Plex-Auto-Collections#227]
Keep getting this error when trying to run the script to update collections:

`Traceback (most recent call last):
  File "D:\Tools\Plex-Auto-Collections\app\plex_auto_collections.py", line 1035, in <module>
    update_from_config(config_path, plex, False)
  File "D:\Tools\Plex-Auto-Collections\app\plex_auto_collections.py", line 668, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, plex_map, map, filters)
  File "D:\Tools\Plex-Auto-Collections\app\plex_tools.py", line 347, in add_to_collection
    current_item.addCollection(c)
  File "C:\Users\spice\AppData\Local\Programs\Python\Python39\lib\site-packages\plexapi\base.py", line 389, in addCollection
    self._edit_tags('collection', collections)
  File "C:\Users\spice\AppData\Local\Programs\Python\Python39\lib\site-packages\plexapi\base.py", line 380, in _edit_tags
    self.edit(**d)
  File "C:\Users\spice\AppData\Local\Programs\Python\Python39\lib\site-packages\plexapi\base.py", line 364, in edit
    self._server.query(part, method=self._server._session.put)
  File "C:\Users\spice\AppData\Local\Programs\Python\Python39\lib\site-packages\plexapi\server.py", line 448, in query
    raise NotFound(message)
plexapi.exceptions.NotFound: (404) not_found; http://192.168.86.245:32400/library/sections/None/all?collection%5B0%5D.tag.tag=1001+Movies+You+Must+See+Before+You+Die&collection.locked=1&id=58052&type=1 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>`

Not entirely sure what is causing the issue .

**Comment by meisnate12** [comment]
development here has stalled check out the updated [Plex Meta Manager](https://github.com/meisnate12/Plex-Meta-Manager). If you're still having the issue there post in the discussions there or join the discord!
