### ISSUE TITLE
plexapi.exceptions.BadRequest: Unknown filter category: actor

### ISSUE THREAD

**Issue by filviu** [mza921/Plex-Auto-Collections#233]
Hi,

First: thanks for picking up this project - I use it a lot. I'm hitting an issue with actor based collections. I read the Read me and tried all the variations I found in the readme:

```yaml
collections:
  Sean Connery:
    actor: Sean Connery

collections:
  Sean Connery:
    actors: Sean Connery

collections:
  Sean Connery:
    plex_search:
      actor: Sean Connery

collections:
  Sean Connery:
    plex_search:
      actors: Sean Connery
```

but in all 4 cases (tried one by one, not all at once) I'm getting the following error:

```
| Sync Mode: sync
| Processing Plex Search: actor(Sean Connery)
Traceback (most recent call last):
  File "/home/user/Plex-Auto-Collections/app/plex_auto_collections.py", line 1026, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "/home/user/Plex-Auto-Collections/app/plex_auto_collections.py", line 668, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, plex_map, map, filters)
  File "/home/user/Plex-Auto-Collections/app/plex_tools.py", line 242, in add_to_collection
    items = plex.Library.search(**search_terms)
  File "/home/user/.local/lib/python3.9/site-packages/plexapi/library.py", line 669, in search
    args[category] = self._cleanSearchFilter(category, value, libtype)
  File "/home/user/.local/lib/python3.9/site-packages/plexapi/library.py", line 717, in _cleanSearchFilter
    raise BadRequest('Unknown filter category: %s' % category)
plexapi.exceptions.BadRequest: Unknown filter category: actor
```

Tried latest git and v2.8.2 python 3.9 and 3.7 all with the same result. Am I doing something wrong ?
Thanks!

**Comment by meisnate12** [comment]
development here has stalled check out the updated [Plex Meta Manager](https://github.com/meisnate12/Plex-Meta-Manager).

**Comment by filviu** [comment]
will do. thanks
