### ISSUE TITLE
Where do I run this script from

### ISSUE THREAD

**Issue by bakedmuffinman** [mza921/Plex-Auto-Collections#237]
I found no mention of where to launch script from ? 

I can only assume I launch from PMS directory ?

would maybe be good to add an error for the ones like me ?

**Comment by bakedmuffinman** [comment]
I ran in PMS folder .\app I ran in PMS folder . and I ran out side of PMS folder and all 3 get error.

| Version 2.9.0
| Locating config...
| Using Y:\Plex Media Server\config.yml as config
|===================================================================================================|
| Connecting to Plex...
Traceback (most recent call last):
  File "plex_auto_collections.py", line 1030, in <module>
    config = Config(config_path)
  File "Y:\Plex Media Server\config_tools.py", line 96, in __init__
    Plex(config_path)
  File "Y:\Plex Media Server\config_tools.py", line 137, in __init__
    config = Config(config_path).plex
  File "Y:\Plex Media Server\config_tools.py", line 86, in __init__
    self.plex = self.data['plex']
TypeError: 'NoneType' object is not subscriptable

**Comment by meisnate12** [comment]
development here has stalled check out the updated [Plex Meta Manager](https://github.com/meisnate12/Plex-Meta-Manager).
