### ISSUE TITLE
Plex unknown filter category : studio

### ISSUE THREAD

**Issue by AthAshino** [mza921/Plex-Auto-Collections#244]
Hello,
I saw that there was an issue about that #78, seems to be corrected with PR #138  but I still have the problem with last version, is it normal? I have both plex and Plex-auto-collections last version (stable version)

```Traceback (most recent call last):
  File "/app/plex_auto_collections.py", line 1026, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "/app/plex_auto_collections.py", line 668, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, plex_map, map, filters)
  File "/app/plex_tools.py", line 242, in add_to_collection
    items = plex.Library.search(**search_terms)
  File "/usr/local/lib/python3.9/site-packages/plexapi/library.py", line 669, in search
    args[category] = self._cleanSearchFilter(category, value, libtype)
  File "/usr/local/lib/python3.9/site-packages/plexapi/library.py", line 717, in _cleanSearchFilter
    raise BadRequest('Unknown filter category: %s' % category)
plexapi.exceptions.BadRequest: Unknown filter category: studio
```

Thank you

EDIT: Sorry didn't mention that I'm using the docker image

**Comment by meisnate12** [comment]
development here has stalled check out the updated [Plex Meta Manager](https://github.com/meisnate12/Plex-Meta-Manager).
