### ISSUE TITLE
Bug: certain IMDb searches fail

### ISSUE THREAD

**Issue by burkasaurusrex** [mza921/Plex-Auto-Collections#58]
Looking into this now:

```
| Processing imdb_list: https://www.imdb.com/search/title/?groups=best_picture_winner&sort=year,desc&count=250
Traceback (most recent call last):
File "plex_auto_collections.py", line 502, in
update_from_config(config_path, plex, True, args.no_meta, args.no_images)
File "plex_auto_collections.py", line 77, in update_from_config
try: missing, map = add_to_collection(config_path, plex, m, v, c, map, subfilters)
File "/app/plex_tools.py", line 135, in add_to_collection
if method == "imdb_list": movies, missing = imdb_tools.imdb_get_movies(config_path, plex, value)
File "/app/imdb_tools.py", line 39, in imdb_get_movies
total = re.findall('(\\d+)', results.group(0))[2]
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by burkasaurusrex** [comment]
Should also add that the script stopped with this error instead of continuing on

**Comment by meisnate12** [comment]
I don't have it catching bugs that shouldn't be happening. This needs a check for when it's only one page should be an easy fix

**Comment by bigdork** [comment]
I understand and am also experiencing the the issues with single-page returns, but larger lists, like the 250 list, are not being created - no error but no collection either.

Snippet from config:
```
  List - IMDb Top 250:
    sort_title: "-4 List - IMDb Top 250"
    imdb_list: https://www.imdb.com/search/title/?groups=top_250
    summary: IMDb's list of the top 250 movies ever made
    poster: https://i.redd.it/gkfygy4k3tr21.jpg
    collection_order: alpha
```

Snippet from output when running:
```
Updating collection: List - IMDb Top 250...
...
| Sync Mode: sync
| 
| Processing imdb_list: https://www.imdb.com/search/title/?groups=top_250
| 250 missing movies from IMDb List: https://www.imdb.com/search/title/?groups=top_250
| Adding missing movies to Radarr
| --- One Flew Over the Cuckoo's Nest: This movie has already been added 400
| --- The Shawshank Redemption: This movie has already been added 400
...
| --- Sherlock Jr.: This movie has already been added 400
| --- The Circus: This movie has already been added 400
| 
| Processing collection_order: alpha
| 
```

**Comment by mza921** [comment]
We could probably use the Beautiful Soup library for the HTML parsing.
