### ISSUE TITLE
Bug: broken pipe error in Linux

### ISSUE THREAD

**Issue by burkasaurusrex** [mza921/Plex-Auto-Collections#65]
Going to be a tough one to debug ... looking into it. Are there any places where we are concatenating long strings before we `print`?

```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.8/http/client.py", line 1049, in _send_output
self.send(chunk)
File "/usr/local/lib/python3.8/http/client.py", line 971, in send
self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 410, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
raise value.with_traceback(tb)
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.8/http/client.py", line 1049, in _send_output
self.send(chunk)
File "/usr/local/lib/python3.8/http/client.py", line 971, in send
self.sock.sendall(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "plex_auto_collections.py", line 502, in
update_from_config(config_path, plex, True, args.no_meta, args.no_images)
File "plex_auto_collections.py", line 288, in update_from_config
else: plex_collection.uploadPoster(filepath=poster[1])
File "/usr/local/lib/python3.8/site-packages/plexapi/library.py", line 1287, in uploadPoster
self._server.query(key, method=self._server._session.post, data=data)
File "/usr/local/lib/python3.8/site-packages/plexapi/server.py", line 440, in query
response = method(url, headers=headers, timeout=timeout, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
```

**Comment by meisnate12** [comment]
what were you doing when it broke?

**Comment by meisnate12** [comment]
whats the collection config for that collection that broke this? i wanna try and reproduce the error on my end

**Comment by burkasaurusrex** [comment]
It's happened a few different places, but here's one of them. I still haven't run it with a debugger yet to figure out where it is tripping.

```yaml
Oscar Winners - Best Picture:
    imdb_list: https://www.imdb.com/search/title/?groups=best_picture_winner&sort=year,desc&count=250
    sync_mode: sync
    summary: The movies that have won an Oscar for best picture (updated every year)
```

**Comment by meisnate12** [comment]
your exact config is working fine for me I can't seem to reproduce your error

**Comment by burkasaurusrex** [comment]
After a bunch of debugging, I think I've found that my system doesn't like to upload images >10MB ... Might be worth noting in the README
