### ISSUE TITLE
Issue syncing the default trakt "Watchlist" into collection

### ISSUE THREAD

**Issue by edrock200** [mza921/Plex-Auto-Collections#72]
Not sure if I'm doing something wrong here but I just pulled the latest version today and setup. When I try to use the default trakt "watchlist" list, I get the error below. If I create a new private list, and add something to it, and update the list in the config, it works. Should this work with the "watchlist" list? Thanks in advance!

(I've changed the usernames below to placeholders)

```Updating collection: Movies To Watch2...
| Sync Mode: sync
| 
| Processing trakt_list: https://trakt.tv/users/*username*/watchlist
Traceback (most recent call last):
  File "./plex_auto_collections.py", line 646, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "./plex_auto_collections.py", line 113, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, map, subfilters)
  File "/Users/macuser/Downloads/Plex-Auto-Collections/app/plex_tools.py", line 143, in add_to_collection
    movies, missing = trakt_tools.trakt_get_movies(config_path, plex, value)
  File "/Users/macuser/Downloads/Plex-Auto-Collections/app/trakt_tools.py", line 13, in trakt_get_movies
    trakt_list_items = trakt.Trakt[trakt_list_path].items()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/trakt/interfaces/base/__init__.py", line 117, in __getattr__
    value = getattr(self.interface, name)
AttributeError: 'UsersWatchlistInterface' object has no attribute 'items'```

**Comment by mza921** [comment]
Trakt watchlists are not currently supported, but I think I can add the functionality.

**Comment by edrock200** [comment]
Thank you!
