### ISSUE TITLE
Enhancement: "Home" release date

### ISSUE THREAD

**Issue by bigdork** [mza921/Plex-Auto-Collections#91]
I'm struggling with a "New Release" collection. This is not new, as it's always been a problem with Plex where the date is the premier or theatrical release date. In the age of COVID, the theatrical and "home" dates have been pretty close, or identical, but traditionally Theatrical date and "Home" date can be months and months apart.

While the recently added `max_age:` is welcome and helpful, it still uses Plex's "release" date.
Could an option be added to use TMDb Digital or Physical dates, or combine them into a combined "home release" date?

https://developers.themoviedb.org/3/movies/get-movie-release-dates

**Comment by meisnate12** [comment]
so im trying to add `tmdb_discover` which uses [this](https://developers.themoviedb.org/3/discover/movie-discover) to filters movies. So once i've finished this you should be able to make a collection based on release date

**Comment by meisnate12** [comment]
@bigdork can you look at the updates and see if `tmdb_discover` will allow you to do what your asking

**Comment by bigdork** [comment]
@meisnate12 I will do!

**Comment by bigdork** [comment]
I guess maybe I don't understand how to use `release_date.gte`? 
Config:
```
    New Releases Test:
        tmdb_discover:
            release_date.gte: 10/01/2020
```
Output:
```
| Updating collection: New Releases Test...
| Sync Mode: sync
| Config Error: Collection New Releases Test not found
| Processing tmdb_discover: 10 items
|            release_date.gte: 2020-10-01
| Cache | + | plex://movie/5f40d8d81ae710004121f964 | tt8648232 | None | Aberdeen
Traceback (most recent call last):
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 986, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 615, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, map, filters)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_tools.py", line 151, in add_to_collection
    movies, missing = imdb_tools.tmdb_get_movies(config_path, plex, value, method)
  File "/opt/scripts/Plex-Auto-Collections/app/imdb_tools.py", line 252, in tmdb_get_movies
    if int(tmdb_id) == int(mid):
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by meisnate12** [comment]
@bigdork can you try using the branch https://github.com/meisnate12/Plex-Auto-Collections/tree/PerformanceUpdate and see if your issue is still occurring

**Comment by bigdork** [comment]
No love. FYI, your branch still reports 2.6.0 in the output when running.

```
:~/Plex-Auto-Collections$ git pull https://github.com/meisnate12/Plex-Auto-Collections.git
From https://github.com/meisnate12/Plex-Auto-Collections
 * branch            HEAD       -> FETCH_HEAD
Already up to date.
:~/Plex-Auto-Collections$ pip3 install --upgrade -r requirements.txt
Requirement already up-to-date: PyYAML==5.3.1 in /home/pg/.local/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (5.3.1)
Requirement already up-to-date: PlexAPI==4.2.0 in /home/pg/.local/lib/python3.6/site-packages (from -r requirements.txt (line 4)) (4.2.0)
Requirement already up-to-date: tmdbv3api==1.6.2 in /home/pg/.local/lib/python3.6/site-packages (from -r requirements.txt (line 5)) (1.6.2)
Requirement already up-to-date: trakt.py==4.2.0 in /home/pg/.local/lib/python3.6/site-packages (from -r requirements.txt (line 6)) (4.2.0)
Requirement already up-to-date: bs4 in /home/pg/.local/lib/python3.6/site-packages (from -r requirements.txt (line 8)) (0.0.1)
Requirement already up-to-date: lxml in /home/pg/.local/lib/python3.6/site-packages (from -r requirements.txt (line 9)) (4.6.1)
Requirement already up-to-date: requests>=2.4.2 in /home/pg/.local/lib/python3.6/site-packages (from -r requirements.txt (line 10)) (2.25.0)
Requirement already up-to-date: ruamel.yaml in /home/pg/.local/lib/python3.6/site-packages (from -r requirements.txt (line 11)) (0.16.12)
Requirement already satisfied, skipping upgrade: six<2.0.0,>=1.10.0 in /home/pg/.local/lib/python3.6/site-packages (from trakt.py==4.2.0->-r requirements.txt (line 6)) (1.15.0)
Requirement already satisfied, skipping upgrade: arrow<1.0.0,>=0.10.0 in /home/pg/.local/lib/python3.6/site-packages (from trakt.py==4.2.0->-r requirements.txt (line 6)) (0.17.0)
Requirement already satisfied, skipping upgrade: beautifulsoup4 in /home/pg/.local/lib/python3.6/site-packages (from bs4->-r requirements.txt (line 8)) (4.9.3)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /home/pg/.local/lib/python3.6/site-packages (from requests>=2.4.2->-r requirements.txt (line 10)) (2.10)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /home/pg/.local/lib/python3.6/site-packages (from requests>=2.4.2->-r requirements.txt (line 10)) (2020.6.20)
Requirement already satisfied, skipping upgrade: urllib3<1.27,>=1.21.1 in /home/pg/.local/lib/python3.6/site-packages (from requests>=2.4.2->-r requirements.txt (line 10)) (1.25.11)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.4.2->-r requirements.txt (line 10)) (3.0.4)
Requirement already satisfied, skipping upgrade: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" in /home/pg/.local/lib/python3.6/site-packages (from ruamel.yaml->-r requirements.txt (line 11)) (0.2.2)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.0 in /home/pg/.local/lib/python3.6/site-packages (from arrow<1.0.0,>=0.10.0->trakt.py==4.2.0->-r requirements.txt (line 6)) (2.8.1)
Requirement already satisfied, skipping upgrade: soupsieve>1.2; python_version >= "3.0" in /home/pg/.local/lib/python3.6/site-packages (from beautifulsoup4->bs4->-r requirements.txt (line 8)) (2.0.1)
:~/Plex-Auto-Collections$ python3 app/plex_auto_collections.py -c /opt/scripts/Plex-Auto-Collections/config/config.mov.test.yml -u


|===================================================================================================|
|     ___  _               _         _           ___       _  _           _    _                    |
|    | _ \| | ___ __ __   /_\  _  _ | |_  ___   / __| ___ | || | ___  __ | |_ (_) ___  _ _   ___    |
|    |  _/| |/ -_)\ \ /  / _ \| || ||  _|/ _ \ | (__ / _ \| || |/ -_)/ _||  _|| |/ _ \| ' \ (_-<    |
|    |_|  |_|\___|/_\_\ /_/ \_\\_,_| \__|\___/  \___|\___/|_||_|\___|\__| \__||_|\___/|_||_|/__/    |
|                                                                                                   |
|===================================================================================================|
| Version 2.6.0
| Locating config...
| Using /opt/scripts/Plex-Auto-Collections/config/config.mov.test.yml as config
|===================================================================================================|
| Connecting to Plex...
| Plex Connection Successful
|===================================================================================================|
| Connecting to TMDb...
| TMDb Connection Successful
|===================================================================================================|
| Connecting to tautulli...
| tautulli connection scuccessful
|===================================================================================================|
| Connecting to Trakt...
| Trakt Connection Successful
|===================================================================================================|
| Connecting to Radarr...
| Radarr Connection Successful
|===================================================================================================|
| image_server attribute not found
|===================================================================================================|
|
| Running collection update press Ctrl+C to abort at anytime
|
|===================================================================================================|
|
| Updating collection: New Releases Test...
| Sync Mode: sync
| Config Error: Collection New Releases Test not found
| Processing tmdb_discover: 10 items
|            release_date.gte: 2020-10-01
| Cache | + | plex://movie/5f40d8d81ae710004121f964 | tt8648232 | None | Aberdeen
Traceback (most recent call last):
  File "app/plex_auto_collections.py", line 986, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "app/plex_auto_collections.py", line 615, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, map, filters)
  File "/home/pg/Plex-Auto-Collections/app/plex_tools.py", line 151, in add_to_collection
    movies, missing = imdb_tools.tmdb_get_movies(config_path, plex, value, method)
  File "/home/pg/Plex-Auto-Collections/app/imdb_tools.py", line 252, in tmdb_get_movies
    if int(tmdb_id) == int(mid):
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by meisnate12** [comment]
i think you're still running the old one mine is updated to 2.6.1 and the order of output shouldn't be possible in my new version

**Comment by meisnate12** [comment]
ahh i see what happened you pulled from my master branch which is at 2.6.0 not the one i sent you try using this

`git checkout PerformanceUpdate` after you pull my whole branch and try again

**Comment by bigdork** [comment]
***d'oh!*** 

```
:~/Plex-Auto-Collections$ git checkout PerformanceUpdate
Branch 'PerformanceUpdate' set up to track remote branch 'PerformanceUpdate' from 'origin'.
Switched to a new branch 'PerformanceUpdate'
Your branch is up to date with 'origin/PerformanceUpdate'.
:~/Plex-Auto-Collections$ python3 app/plex_auto_collections.py -c config/config.mov.test.yml -u

|===================================================================================================|
|     ___  _               _         _           ___       _  _           _    _                    |
|    | _ \| | ___ __ __   /_\  _  _ | |_  ___   / __| ___ | || | ___  __ | |_ (_) ___  _ _   ___    |
|    |  _/| |/ -_)\ \ /  / _ \| || ||  _|/ _ \ | (__ / _ \| || |/ -_)/ _||  _|| |/ _ \| ' \ (_-<    |
|    |_|  |_|\___|/_\_\ /_/ \_\\_,_| \__|\___/  \___|\___/|_||_|\___|\__| \__||_|\___/|_||_|/__/    |
|                                                                                                   |
|===================================================================================================|
| Version 2.6.1
| Locating config...
| Using /home/pg/Plex-Auto-Collections/config/config.mov.test.yml as config
|===================================================================================================|
| Connecting to Plex...
| Plex Connection Successful
|===================================================================================================|
| Connecting to TMDb...
| TMDb Connection Successful
|===================================================================================================|
| Connecting to tautulli...
| tautulli connection scuccessful
|===================================================================================================|
| Connecting to Trakt...
| Trakt Connection Successful
|===================================================================================================|
| Connecting to Radarr...
| Radarr Connection Successful
|===================================================================================================|
| image_server attribute not found
|===================================================================================================|
|
| Processing Plex Movies
Traceback (most recent call last):
  File "app/plex_auto_collections.py", line 993, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "app/plex_auto_collections.py", line 115, in update_from_config
    plex_map = get_movie_map(config_path, plex)
  File "/home/pg/Plex-Auto-Collections/app/plex_tools.py", line 114, in get_movie_map
    create_cache()
TypeError: create_cache() missing 1 required positional argument: 'config_path'
```

**Comment by meisnate12** [comment]
do a git pull on that branch

**Comment by bigdork** [comment]
I am most-definitely a "user" but am figuring it out.
It's rolling through the process now, no crash

**Comment by meisnate12** [comment]
haha its all good I appreciate you testing all this. let me know how it goes!

**Comment by bigdork** [comment]
Ok, that finished!  Looks like this requires me to set a date, though. If I wanted to run this monthly, I'd need to change the `release_date.gte` for a specific date, instead of a way to say "last 90 days" or the like?

**Comment by meisnate12** [comment]
for that you would have to use the subfilter option

**Comment by meisnate12** [comment]
the people who do the plex api were talking about trying to include operators in the plex search (ie using <>!) and if that happen we will be able to implement the release date into `plex_search`

**Comment by meisnate12** [comment]
waiting on this pull request [pkkid/python-plexapi/pull/598](https://github.com/pkkid/python-plexapi/pull/598)

**Comment by bigdork** [comment]
Circled back around to the script, the "Cache" phase completed, the "Adding-to-Collection" phase completed, the "Adding-to-Radarr" phase appears to have completed, then the script crashed.
```
...
| --- Dersu Uzala: This movie has already been added 400
| --- 30 jours max: This movie has already been added 400
Traceback (most recent call last):
  File "app/plex_auto_collections.py", line 1002, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "app/plex_auto_collections.py", line 652, in update_from_config
    add_to_radarr(config_path, missing)
  File "/home/pg/Plex-Auto-Collections/app/radarr_tools.py", line 17, in add_to_radarr
    search = movie.external(external_id=str(m), external_source="imdb_id")['movie_results']
  File "/home/pg/.local/lib/python3.6/site-packages/tmdbv3api/objs/movie.py", line 185, in external
    key=None,
  File "/home/pg/.local/lib/python3.6/site-packages/tmdbv3api/tmdb.py", line 101, in _get_obj
    raise Exception(result["status_message"])
Exception: The resource you requested could not be found.
```

**Comment by meisnate12** [comment]
can you add some code in  radarr_tools.py at line 17 and run again 

original code
```python
16        # Get TMDb ID data from IMDb ID
17        search = movie.external(external_id=str(m), external_source="imdb_id")['movie_results']
```

modified code
```python
16        # Get TMDb ID data from IMDb ID
17        print(str(m))
18        search = movie.external(external_id=str(m), external_source="imdb_id")['movie_results']
```

**Comment by bigdork** [comment]
Inserted line 17 and re-ran.
The script completed!

**Comment by meisnate12** [comment]
tbh i have no idea why it failed before and why its working now but im not mad at it lol all what you added was a print to help figure out what happened not any kind of fix
