### ISSUE TITLE
Trakt and IMDb movie lists still not working with new agent

### ISSUE THREAD

**Issue by bigdork** [mza921/Plex-Auto-Collections#92]
I thought I read this problem was resolved recently, but Trakt and IMDb lists still are not working for me with the new movie agent. Trakt lists fail with 403 and crash the script, IMDb lists fail to locate movies or build the collection. Is this still expected behavior with Version 2.4.2?

Couple examples of each, from the README.

Config:
```
  Trending:
    trakt_trending: 30
```
Output:
```
 Updating collection: Trending...
| Sync Mode: sync
| 
| Processing trakt_trending: 3
Traceback (most recent call last):
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 819, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 450, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, map, filters)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_tools.py", line 160, in add_to_collection
    movies, missing = trakt_tools.trakt_get_movies(config_path, plex, value, is_userlist=False)
  File "/opt/scripts/Plex-Auto-Collections/app/trakt_tools.py", line 30, in trakt_get_movies
    imdb_id, tmdb_id = plex_tools.alt_id_lookup(plex, item)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_tools.py", line 355, in alt_id_lookup
    with urlopen(req) as response:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

Config:
```
  Christmas Movies:
    trakt_list:
      - https://trakt.tv/users/movistapp/lists/christmas-movies
      - https://trakt.tv/users/2borno2b/lists/christmas-movies-extravanganza
```
Output:
```
| Updating collection: Christmas Movies...
| Sync Mode: sync
| 
| Processing trakt_list: https://trakt.tv/users/movistapp/lists/christmas-movies
Traceback (most recent call last):
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 819, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 450, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, map, filters)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_tools.py", line 158, in add_to_collection
    movies, missing = trakt_tools.trakt_get_movies(config_path, plex, value)
  File "/opt/scripts/Plex-Auto-Collections/app/trakt_tools.py", line 30, in trakt_get_movies
    imdb_id, tmdb_id = plex_tools.alt_id_lookup(plex, item)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_tools.py", line 355, in alt_id_lookup
    with urlopen(req) as response:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

Config:
```
  IMDb Top 250:
    imdb_list: https://www.imdb.com/search/title/?groups=top_250
```
Output:
```
| Updating collection: IMDb Top 250...
| Sync Mode: sync
| 
| Processing imdb_list: https://www.imdb.com/search/title/?groups=top_250
... insert massive pause here...
| No movies found
| 250 missing movies from IMDb List: https://www.imdb.com/search/title/?groups=top_250
| Adding missing movies to Radarr
| --- Rebecca: This movie has already been added 400
| --- The Shining: This movie has already been added 400
| --- Parasite: This movie has already been added 400
| --- 1917: This movie has already been added 400
| --- Joker: This movie has already been added 400
... repeat 245 more times...
```

Config:
```
  James Bond - Daniel Craig:
    imdb_list: https://www.imdb.com/list/ls006405458/
    filters:
      actor: Daniel Craig
```
Output:
```
| Updating collection: James Bond - Daniel Craig...
| Sync Mode: sync
| 
|  Collection Filter actor: Daniel Craig
| 
| Processing imdb_list: https://www.imdb.com/list/ls006405458/
... insert massive pause here...
| No movies found
| 28 missing movies from IMDb List: https://www.imdb.com/list/ls006405458/
| Adding missing movies to Radarr
| --- Casino Royale: This movie has already been added 400
| --- Dr. No: This movie has already been added 400
| --- From Russia with Love: This movie has already been added 400
... repeat 25 more times, including all Bond not just Craig...
```

**Comment by jalarab** [comment]
In my case with 2.4.5 IMDB list works but only with the first 100 items of the list

**Comment by meisnate12** [comment]
I'm still trying to figure out whats going on with both trakt and imdb lists its really hard because all these lists work for me correctly for me i cannot replicate your errors 

Also @jalarab mine work with more then 100 i cant get it to not

**Comment by jalarab** [comment]
In my case, it works withs carts, like IMDB top 250 but not with lists. maybe you can tell me which list are you using, and I can try

**Comment by meisnate12** [comment]
can you paste the link to which list is failing again?

**Comment by jalarab** [comment]
Now the behavior is weird. This list has 472 items.
https://www.imdb.com/search/title/?lists=ls023764240&count=250
The script adds 387 but said that I have 301 missing movies
[list.txt](https://github.com/mza921/Plex-Auto-Collections/files/5503807/list.txt)
but if if run same list but with search
https://www.imdb.com/search/title/?lists=ls023764240&count=250
It works well
[search.txt](https://github.com/mza921/Plex-Auto-Collections/files/5503809/search.txt)

**Comment by meisnate12** [comment]
can you download and try using my branch [meisnate12/Plex-Auto-Collections](https://github.com/meisnate12/Plex-Auto-Collections) and send me the output it gives you

**Comment by meisnate12** [comment]
i do finally know your issue tho its because your using
https://www.imdb.com/list/ls023764240/?sort=list_order,desc
instead of 
https://www.imdb.com/list/ls023764240/

**Comment by meisnate12** [comment]
please update to 2.4.6 and try and see if it works now I think I've got it working correctly

**Comment by bigdork** [comment]
No change for me. 

Tested with the same list configs from original post:
- Tmdb lists error 403.
- IMDb lists run for-ev-er and "No movies found" then try to add to Radarr where they already exist.

**Comment by meisnate12** [comment]
the output should be a little different in the new version can you run it and paste your entire output

**Comment by mza921** [comment]
If you are getting a 403, you can try re-initializing your Trakt creds. Just wipe out the values in the authorization section and run the script without `--update`.

**Comment by bigdork** [comment]
@meisnate12 

Version 2.4.6

I reset my trakt config:
```
| Connecting to Trakt...
| Stored Authorization Failed
| Navigate to: https://trakt.tv/oauth/authorize?client_id=redacted&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code
| If you get an OAuth error your client_id or client_secret is invalid
| trakt pin (case insensitive): 0E53D12B
| Saving authorization information to /opt/scripts/Plex-Auto-Collections/config/config.mov.lists.yml
| Trakt Connection Successful
```
But still 403 at trakt.

Config:
```
    Christmas Movies:
        sort_title: -4 Christmas Movies
        summary: A collection of Christmas movies
        collection_order: alpha
        trakt_list:
          - https://trakt.tv/users/movistapp/lists/christmas-movies
          - https://trakt.tv/users/2borno2b/lists/christmas-movies-extravanganza
```
Output:
```
| Updating collection: Christmas Movies...
| Sync Mode: sync
|
| Processing trakt_list: https://trakt.tv/users/movistapp/lists/christmas-movies
Traceback (most recent call last):
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 838, in <module>
    update_from_config(config_path, plex, False)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 461, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, map, filters)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_tools.py", line 158, in add_to_collection
    movies, missing = trakt_tools.trakt_get_movies(config_path, plex, value)
  File "/opt/scripts/Plex-Auto-Collections/app/trakt_tools.py", line 30, in trakt_get_movies
    imdb_id, tmdb_id = plex_tools.alt_id_lookup(plex, item)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_tools.py", line 369, in alt_id_lookup
    with urlopen(req) as response:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```
For IMDB, added a year filter so it would run more quickly.
Config:
```
  James Bond Daniel Craig:
    imdb_list: https://www.imdb.com/list/ls006405458/
    filters:
      actor: Daniel Craig
```
Output:
```
 Updating collection: James Bond Daniel Craig...
| Sync Mode: sync
|
| Collection Filter actor: Daniel Craig
|
| Processing imdb_list: https://www.imdb.com/list/ls006405458/
| 28 Movies found on IMDb
(Insert long pause here while the next line cycles through entire movie library...)
| Processing: x/24914 Moviename
| Processed 24914 Movies
| No movies found
| 28 missing movies from IMDb List: https://www.imdb.com/list/ls006405458/
| Adding missing movies to Radarr
| --- Casino Royale: This movie has already been added 400
| --- Dr. No: This movie has already been added 400
| --- From Russia with Love: This movie has already been added 400
| --- Goldfinger: This movie has already been added 400
| --- Thunderball: This movie has already been added 400
| --- You Only Live Twice: This movie has already been added 400
| --- Casino Royale: This movie has already been added 400
| --- On Her Majesty's Secret Service: This movie has already been added 400
| --- Diamonds Are Forever: This movie has already been added 400
| --- Live and Let Die: This movie has already been added 400
| --- The Man with the Golden Gun: This movie has already been added 400
| --- The Spy Who Loved Me: This movie has already been added 400
| --- Moonraker: This movie has already been added 400
| --- For Your Eyes Only: This movie has already been added 400
| --- Octopussy: This movie has already been added 400
| --- Never Say Never Again: This movie has already been added 400
| --- A View to a Kill: This movie has already been added 400
| --- The Living Daylights: This movie has already been added 400
| --- Licence to Kill: This movie has already been added 400
| --- GoldenEye: This movie has already been added 400
| --- Tomorrow Never Dies: This movie has already been added 400
| --- The World Is Not Enough: This movie has already been added 400
| --- Die Another Day: This movie has already been added 400
| --- Casino Royale: This movie has already been added 400
| --- Quantum of Solace: This movie has already been added 400
| --- Skyfall: This movie has already been added 400
| --- Spectre: This movie has already been added 400
| --- No Time to Die: This movie has already been added 400
|
```

**Comment by meisnate12** [comment]
@mza921 for the imdb movies from what i can tell the try statement in the for loop below might be catching some error thats cause all this to fail so we should try and take out the except all and catch the specific errors that we think might show up instead of everything. 

@bigdork im going to push an update to my branch [here](https://github.com/meisnate12/Plex-Auto-Collections) removing this try so we can see what you error with imdb is try mine and run this again please

```python
for m in plex_movies:
        current_count += 1
        print_display = "| Processing: {}/{} {}".format(current_count, len(plex_movies), m.title)
        print(adjust_space(current_length, print_display), end="\r")
        current_length = len(print_display)
        try:
            if 'plex://' in m.guid:
                item = m
                # Check cache for imdb_id
                imdb_id = plex_tools.query_cache(config_path, item.guid, 'imdb_id')
                if not imdb_id:
                    imdb_id, tmdb_id = plex_tools.alt_id_lookup(plex, item)
                    print(adjust_space(current_length, "| Cache | + | {} | {} | {} | {}".format(item.guid, imdb_id, tmdb_id, item.title)))
                    plex_tools.update_cache(config_path, item.guid, imdb_id=imdb_id, tmdb_id=tmdb_id)
            elif 'themoviedb://' in m.guid:
                if not tmdb.api_key == "None":
                    tmdb_id = m.guid.split('themoviedb://')[1].split('?')[0]
                    tmdbapi = movie.details(tmdb_id)
                    imdb_id = tmdbapi.imdb_id
                else:
                    imdb_id = None
            elif 'imdb://' in m.guid:
                imdb_id = m.guid.split('imdb://')[1].split('?')[0]
            else:
                imdb_id = None
        except:
            imdb_id = None

        if imdb_id and imdb_id in title_ids:
            imdb_map[imdb_id] = m
        else:
            imdb_map[m.ratingKey] = m
```

**Comment by bigdork** [comment]
Pulled https://github.com/meisnate12/Plex-Auto-Collections.git
First run output using the same Bond list from above:
| Updating collection: James Bond Daniel Craig...
| Sync Mode: sync
|
| Collection Filter actor: Daniel Craig
|
| Processing imdb_list: https://www.imdb.com/list/ls006405458/
| 28 Movies found on IMDb
| Initializing cache database.
Traceback (most recent call last):
```
  File "/home/pg/Plex-Auto-Collections/app/plex_auto_collections.py", line 830, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "/home/pg/Plex-Auto-Collections/app/plex_auto_collections.py", line 461, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, map, filters)
  File "/home/pg/Plex-Auto-Collections/app/plex_tools.py", line 154, in add_to_collection
    movies, missing = imdb_tools.imdb_get_movies(config_path, plex, value)
  File "/home/pg/Plex-Auto-Collections/app/imdb_tools.py", line 91, in imdb_get_movies
    imdb_id, tmdb_id = plex_tools.alt_id_lookup(plex, item)
  File "/home/pg/Plex-Auto-Collections/app/plex_tools.py", line 369, in alt_id_lookup
    with urlopen(req) as response:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

Ran it again, output looks the same except no "Initializing cache database"
```
| Updating collection: James Bond Daniel Craig...
| Sync Mode: sync
|
| Collection Filter actor: Daniel Craig
|
| Processing imdb_list: https://www.imdb.com/list/ls006405458/
| 28 Movies found on IMDb
Traceback (most recent call last):
  File "/home/pg/Plex-Auto-Collections/app/plex_auto_collections.py", line 830, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "/home/pg/Plex-Auto-Collections/app/plex_auto_collections.py", line 461, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, map, filters)
  File "/home/pg/Plex-Auto-Collections/app/plex_tools.py", line 154, in add_to_collection
    movies, missing = imdb_tools.imdb_get_movies(config_path, plex, value)
  File "/home/pg/Plex-Auto-Collections/app/imdb_tools.py", line 91, in imdb_get_movies
    imdb_id, tmdb_id = plex_tools.alt_id_lookup(plex, item)
  File "/home/pg/Plex-Auto-Collections/app/plex_tools.py", line 369, in alt_id_lookup
    with urlopen(req) as response:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by meisnate12** [comment]
yea i thought that you were getting the same error on imdb as trakt i just needed to confirm that the issue is the same 403 Error

A 403 HTTP Error means access to the requested resource is forbidden for some reason. That reason i could only guess at but basically the script is not being giving access to plex both errors are failing in the same place where the script connects to plex. I cannot personally test this as i don't have anything set up with the new plex movie agent, but since it appears to be working for others. There might be some kind of permission issue on your network that is blocking these requests.

**Comment by bigdork** [comment]
Interesting, because most other configs work, and trakt trending works with TV shows. 
Any idea how that could be?

**Comment by meisnate12** [comment]
it has to do with how we do the request for the imdb_id when your'e using the new movie agent only thats why tv shows and the others still work

**Comment by bigdork** [comment]
@meisnate12 - Makes sense, I will try to troubleshoot further

**Comment by mza921** [comment]
Are you running a web server/reverse proxy in front of Plex? Can you try adding a line below this in `plex_tools.py` https://github.com/mza921/Plex-Auto-Collections/blob/d58fb288bd9b746ff423816bb3a82ec365b092c3/app/plex_tools.py#L368 

Add:
```
    req.add_header('User-Agent', 'Mozilla/5.0')
```

**Comment by bigdork** [comment]
Yes I am, traefik is sitting in front of plex.

I added that line at 369 and I don't wanna get my hopes up, but stuff is happening!
```
| Cache | + | plex://movie/5d776824a091de001f2e6020 | tt0062622 | 62 | 2001: A Space Odyssey
| Cache | + | plex://movie/5d7768313c3c2a001fbcd28d | tt0157262 | 7290 | 2001: A Space Travesty
| Cache | + | plex://movie/5d77682df54112001f5bca63 | tt0086837 | 4437 | 2010
| Cache | + | plex://movie/5d77688af617c9002015508a | tt1694508 | 50053 | 2010: Moby Dick
| Cache | + | plex://movie/5d77683bf59e580021899679 | tt1190080 | 14161 | 2012
| Cache | + | plex://movie/5d77683eeb5d26001f1e2f71 | tt1132130 | 16266 | 2012 Doomsday
```

**Comment by meisnate12** [comment]
@mza921 ill add that line in and submit a pull for this fix and another give me like 15 min

**Comment by bigdork** [comment]
Heads up - NO RUSH, I'm heading into meetings for pretty much the remainder of the workday (USA Eastern), but I'll circle back to this this evening. Going to let this Cache process continue to run in the background and hope to eventually see the Trakt trending list succeed, then I'll see if IMDB is working also (I suspect it is)

**Comment by mza921** [comment]
Reference: https://stackoverflow.com/questions/16627227/http-error-403-in-python-3-web-scraping
