### ISSUE TITLE
Filter "max_age" not working for shows?

### ISSUE THREAD

**Issue by bigdork** [mza921/Plex-Auto-Collections#93]
This same config works for movies, but not for TV.
I also tried replacing `all: true` with `year: 2020` with the same results.
If I remove this section of the config, the rest of the script executes, so I don't think there's any problem with the Plex config.

Config:
```
  New Releases:
    sort_title: -0 New Releases
    summary: A collection of new shows that have premiered in the last 6 months
    all: true
    filters:
      max_age: 180
...
plex:
  library: TV Shows
  library_type: show   ### 'movie' or 'show' ###
  token: _REDACTED_
  url: https://plexserveraddress
  sync_mode: sync   ### 'sync' or 'append' ###
```
Output:
```
| Updating collection: New Releases...
| Sync Mode: sync
| 
|  Collection Filter max_age: 180
| 
| Processing all: 
Traceback (most recent call last):
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 819, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 450, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, map, filters)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_tools.py", line 287, in add_to_collection
    max_age = imdb_tools.regex_first_int(sf[1])
AttributeError: module 'imdb_tools' has no attribute 'regex_first_int'
```

**Comment by mza921** [comment]
@meisnate12 Still broken...
```
Traceback (most recent call last):
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 819, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 450, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, map, filters)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_tools.py", line 300, in add_to_collection
    max_age = regex_first_int(sf[1])
TypeError: regex_first_int() missing 1 required positional argument: 'method'
```

**Comment by bigdork** [comment]
Version 2.4.5

For TV, no longer crashes but still doesn't work. Seems `max_age:` it is ignored?
With `all: true` it attempts to add every show in the library. 
With `year: 2000` it attempts to add every 2020 TV show.

Config:
```
  New Releases:
    sort_title: -0 New Releases
    summary: A collection of new shows that have premiered in the last 6 months
    #all: true
    year: 2020
    filters:
      max_age: 180
```
Output:
```
| Updating collection: New Releases...
| Sync Mode: sync
|
|  Collection Filter max_age: 180
|
| Processing Plex Search: year(2020)
| Processing Plex Search: year(2020)
| New Releases Collection | + | 100 Humans
| New Releases Collection | + | 50 States of Fright
| New Releases Collection | + | 68 Whiskey
^C
```
Release Dates:
- 100 Humans = 2020-03-13
- 50 States of Fright = 2020-04-06
- 68 Whiskey = 2020-01-15

**Comment by meisnate12** [comment]
all show filters are currently broken will fix soon

**Comment by meisnate12** [comment]
ok please update to 2.4.6 and try and see if it works now I think I've got it working correctly

**Comment by bigdork** [comment]
Version 2.4.6
`max_age:` appears to be working properly for TV Shows! Thank you!
